player.tab.line_88.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_88.setObjectName("line_88")
player.tab.gridLayout_4.addWidget(player.tab.line_88, 12, 1, 1, 1)
player.tab.line_101 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_101.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_101.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_101.setObjectName("line_101")
player.tab.gridLayout_4.addWidget(player.tab.line_101, 5, 0, 1, 1)
player.tab.magic_checkbox = QtWidgets.QCheckBox(player.tab.gridLayoutWidget_4)
player.tab.magic_checkbox.setObjectName("magic_checkbox")
player.tab.gridLayout_4.addWidget(player.tab.magic_checkbox, 6, 2, 1, 1)
player.tab.line_91 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_91.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_91.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_91.setObjectName("line_91")
player.tab.gridLayout_4.addWidget(player.tab.line_91, 13, 6, 1, 1)
player.tab.line_103 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_103.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_103.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_103.setObjectName("line_103")
player.tab.gridLayout_4.addWidget(player.tab.line_103, 13, 2, 1, 1)
player.tab.analiz_checkbox = QtWidgets.QCheckBox(player.tab.gridLayoutWidget_4)
player.tab.analiz_checkbox.setObjectName("analiz_checkbox")
player.tab.gridLayout_4.addWidget(player.tab.analiz_checkbox, 2, 2, 1, 1)
player.tab.line_97 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_97.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_97.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_97.setObjectName("line_97")
player.tab.gridLayout_4.addWidget(player.tab.line_97, 3, 2, 1, 1)
player.tab.line_113 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_113.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_113.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_113.setObjectName("line_113")
player.tab.gridLayout_4.addWidget(player.tab.line_113, 3, 5, 1, 1)
player.tab.magic_checkboxhaving = QtWidgets.QCheckBox(player.tab.gridLayoutWidget_4)
player.tab.magic_checkboxhaving.setObjectName("magic_checkboxhaving")
player.tab.gridLayout_4.addWidget(player.tab.magic_checkboxhaving, 6, 4, 1, 1)
player.tab.line_86 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_86.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_86.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_86.setObjectName("line_86")
player.tab.gridLayout_4.addWidget(player.tab.line_86, 1, 2, 1, 1)
player.tab.line_111 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_111.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_111.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_111.setObjectName("line_111")
player.tab.gridLayout_4.addWidget(player.tab.line_111, 13, 3, 1, 1)
player.tab.line_82 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_82.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_82.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_82.setObjectName("line_82")
player.tab.gridLayout_4.addWidget(player.tab.line_82, 7, 2, 1, 1)
player.tab.line_77 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_77.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_77.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_77.setObjectName("line_77")
player.tab.gridLayout_4.addWidget(player.tab.line_77, 13, 4, 1, 1)
player.tab.line_83 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_83.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_83.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_83.setObjectName("line_83")
player.tab.gridLayout_4.addWidget(player.tab.line_83, 7, 6, 1, 1)
player.tab.line_90 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_90.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_90.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_90.setObjectName("line_90")
player.tab.gridLayout_4.addWidget(player.tab.line_90, 13, 0, 1, 1)
player.tab.line_99 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_99.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_99.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_99.setObjectName("line_99")
player.tab.gridLayout_4.addWidget(player.tab.line_99, 3, 3, 1, 1)
player.tab.analiz_labl = QtWidgets.QLabel(player.tab.gridLayoutWidget_4)
player.tab.analiz_labl.setObjectName("analiz_labl")
player.tab.gridLayout_4.addWidget(player.tab.analiz_labl, 2, 0, 1, 1)
player.tab.line_106 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_106.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_106.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_106.setObjectName("line_106")
player.tab.gridLayout_4.addWidget(player.tab.line_106, 7, 4, 1, 1)
player.tab.save_giving_intellect_checkboxhaving = QtWidgets.QCheckBox(player.tab.gridLayoutWidget_4)
player.tab.save_giving_intellect_checkboxhaving.setObjectName("save_giving_intellect_checkboxhaving")
player.tab.gridLayout_4.addWidget(player.tab.save_giving_intellect_checkboxhaving, 12, 4, 1, 1)
player.tab.nature_labl = QtWidgets.QLabel(player.tab.gridLayoutWidget_4)
player.tab.nature_labl.setObjectName("nature_labl")
player.tab.gridLayout_4.addWidget(player.tab.nature_labl, 8, 0, 1, 1)
player.tab.line_102 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_102.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_102.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_102.setObjectName("line_102")
player.tab.gridLayout_4.addWidget(player.tab.line_102, 5, 4, 1, 1)
player.tab.magic_labl = QtWidgets.QLabel(player.tab.gridLayoutWidget_4)
player.tab.magic_labl.setObjectName("magic_labl")
player.tab.gridLayout_4.addWidget(player.tab.magic_labl, 6, 0, 1, 1)
player.tab.line_89 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_89.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_89.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_89.setObjectName("line_89")
player.tab.gridLayout_4.addWidget(player.tab.line_89, 2, 1, 1, 1)
player.tab.znachenie_intellect_labl = QtWidgets.QLabel(player.tab.gridLayoutWidget_4)
player.tab.znachenie_intellect_labl.setObjectName("znachenie_intellect_labl")
player.tab.gridLayout_4.addWidget(player.tab.znachenie_intellect_labl, 0, 0, 1, 1)
player.tab.line_112 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_112.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_112.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_112.setObjectName("line_112")
player.tab.gridLayout_4.addWidget(player.tab.line_112, 13, 5, 1, 1)
player.tab.line_116 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_116.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_116.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_116.setObjectName("line_116")
player.tab.gridLayout_4.addWidget(player.tab.line_116, 9, 0, 1, 1)
player.tab.line_117 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_117.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_117.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_117.setObjectName("line_117")
player.tab.gridLayout_4.addWidget(player.tab.line_117, 9, 2, 1, 1)
player.tab.line_118 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_118.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_118.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_118.setObjectName("line_118")
player.tab.gridLayout_4.addWidget(player.tab.line_118, 11, 2, 1, 1)
player.tab.line_119 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_119.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_119.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_119.setObjectName("line_119")
player.tab.gridLayout_4.addWidget(player.tab.line_119, 11, 4, 1, 1)
player.tab.line_120 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_120.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_120.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_120.setObjectName("line_120")
player.tab.gridLayout_4.addWidget(player.tab.line_120, 9, 4, 1, 1)
player.tab.line_121 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_121.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_121.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_121.setObjectName("line_121")
player.tab.gridLayout_4.addWidget(player.tab.line_121, 9, 6, 1, 1)
player.tab.line_122 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_122.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_122.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_122.setObjectName("line_122")
player.tab.gridLayout_4.addWidget(player.tab.line_122, 11, 6, 1, 1)
player.tab.nature_checkbox = QtWidgets.QCheckBox(player.tab.gridLayoutWidget_4)
player.tab.nature_checkbox.setObjectName("nature_checkbox")
player.tab.gridLayout_4.addWidget(player.tab.nature_checkbox, 8, 2, 1, 1)
player.tab.religion_checkbox = QtWidgets.QCheckBox(player.tab.gridLayoutWidget_4)
player.tab.religion_checkbox.setObjectName("religion_checkbox")
player.tab.gridLayout_4.addWidget(player.tab.religion_checkbox, 10, 2, 1, 1)
player.tab.nature_checkboxhaving = QtWidgets.QCheckBox(player.tab.gridLayoutWidget_4)
player.tab.nature_checkboxhaving.setObjectName("nature_checkboxhaving")
player.tab.gridLayout_4.addWidget(player.tab.nature_checkboxhaving, 8, 4, 1, 1)
player.tab.religion_checkboxhaving = QtWidgets.QCheckBox(player.tab.gridLayoutWidget_4)
player.tab.religion_checkboxhaving.setObjectName("religion_checkboxhaving")
player.tab.gridLayout_4.addWidget(player.tab.religion_checkboxhaving, 10, 4, 1, 1)
player.tab.nature_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_4)
player.tab.nature_field.setObjectName("nature_field")
player.tab.gridLayout_4.addWidget(player.tab.nature_field, 8, 6, 1, 1)
player.tab.religion_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_4)
player.tab.religion_field.setObjectName("religion_field")
player.tab.gridLayout_4.addWidget(player.tab.religion_field, 10, 6, 1, 1)
player.tab.description_intellect_labl = QtWidgets.QLabel(player.tab.characteristics_intellect)
player.tab.description_intellect_labl.setGeometry(QtCore.QRect(10, 250, 311, 191))
player.tab.description_intellect_labl.setTextFormat(QtCore.Qt.PlainText)
player.tab.description_intellect_labl.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
player.tab.description_intellect_labl.setObjectName("description_intellect_labl")
player.tab.caractersistics.addTab(player.tab.characteristics_intellect, "")
player.tab.characteristics_wise = QtWidgets.QWidget()
player.tab.characteristics_wise.setObjectName("characteristics_wise")
player.tab.gridLayoutWidget_5 = QtWidgets.QWidget(player.tab.characteristics_wise)
player.tab.gridLayoutWidget_5.setGeometry(QtCore.QRect(0, 0, 311, 256))
player.tab.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
player.tab.gridLayout_5 = QtWidgets.QGridLayout(player.tab.gridLayoutWidget_5)
player.tab.gridLayout_5.setContentsMargins(10, 0, 0, 0)
player.tab.gridLayout_5.setObjectName("gridLayout_5")
player.tab.living_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_5)
player.tab.living_field.setObjectName("living_field")
player.tab.gridLayout_5.addWidget(player.tab.living_field, 4, 6, 1, 1)
player.tab.mod_wise_labl = QtWidgets.QLabel(player.tab.gridLayoutWidget_5)
player.tab.mod_wise_labl.setObjectName("mod_wise_labl")
player.tab.gridLayout_5.addWidget(player.tab.mod_wise_labl, 0, 4, 1, 1)
player.tab.mod_wise_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_5)
player.tab.mod_wise_field.setObjectName("mod_wise_field")
player.tab.gridLayout_5.addWidget(player.tab.mod_wise_field, 0, 6, 1, 1)
player.tab.line_123 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_123.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_123.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_123.setObjectName("line_123")
player.tab.gridLayout_5.addWidget(player.tab.line_123, 0, 3, 1, 1)
player.tab.mindfulness_checkboxhaving = QtWidgets.QCheckBox(player.tab.gridLayoutWidget_5)
player.tab.mindfulness_checkboxhaving.setObjectName("mindfulness_checkboxhaving")
player.tab.gridLayout_5.addWidget(player.tab.mindfulness_checkboxhaving, 2, 4, 1, 1)
player.tab.line_124 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_124.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_124.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_124.setObjectName("line_124")
player.tab.gridLayout_5.addWidget(player.tab.line_124, 12, 5, 1, 1)
player.tab.save_giving_wise_labl = QtWidgets.QLabel(player.tab.gridLayoutWidget_5)
player.tab.save_giving_wise_labl.setObjectName("save_giving_wise_labl")
player.tab.gridLayout_5.addWidget(player.tab.save_giving_wise_labl, 12, 0, 1, 1)
player.tab.line_125 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_125.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_125.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_125.setObjectName("line_125")
player.tab.gridLayout_5.addWidget(player.tab.line_125, 3, 1, 1, 1)
player.tab.care_of_animal_labl = QtWidgets.QLabel(player.tab.gridLayoutWidget_5)
player.tab.care_of_animal_labl.setObjectName("care_of_animal_labl")
player.tab.gridLayout_5.addWidget(player.tab.care_of_animal_labl, 10, 0, 1, 1)
player.tab.line_126 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_126.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_126.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_126.setObjectName("line_126")
player.tab.gridLayout_5.addWidget(player.tab.line_126, 3, 0, 1, 1)
player.tab.line_127 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_127.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_127.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_127.setObjectName("line_127")
player.tab.gridLayout_5.addWidget(player.tab.line_127, 1, 6, 1, 1)
player.tab.line_128 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_128.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_128.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_128.setObjectName("line_128")
player.tab.gridLayout_5.addWidget(player.tab.line_128, 5, 6, 1, 1)
player.tab.line_129 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_129.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_129.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_129.setObjectName("line_129")
player.tab.gridLayout_5.addWidget(player.tab.line_129, 2, 3, 1, 1)
player.tab.line_130 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_130.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_130.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_130.setObjectName("line_130")
player.tab.gridLayout_5.addWidget(player.tab.line_130, 11, 0, 1, 1)
player.tab.line_131 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_131.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_131.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_131.setObjectName("line_131")
player.tab.gridLayout_5.addWidget(player.tab.line_131, 13, 1, 1, 1)
player.tab.line_132 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_132.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_132.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_132.setObjectName("line_132")
player.tab.gridLayout_5.addWidget(player.tab.line_132, 2, 5, 1, 1)
player.tab.mindfulness_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_5)
player.tab.mindfulness_field.setObjectName("mindfulness_field")
player.tab.gridLayout_5.addWidget(player.tab.mindfulness_field, 2, 6, 1, 1)
player.tab.line_133 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_133.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_133.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_133.setObjectName("line_133")
player.tab.gridLayout_5.addWidget(player.tab.line_133, 3, 4, 1, 1)
player.tab.medicine_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_5)
player.tab.medicine_field.setObjectName("medicine_field")
player.tab.gridLayout_5.addWidget(player.tab.medicine_field, 6, 6, 1, 1)
player.tab.znachenie_wise_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_5)
player.tab.znachenie_wise_field.setObjectName("znachenie_wise_field")
player.tab.gridLayout_5.addWidget(player.tab.znachenie_wise_field, 0, 2, 1, 1)
player.tab.line_134 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_134.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_134.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_134.setObjectName("line_134")
player.tab.gridLayout_5.addWidget(player.tab.line_134, 1, 1, 1, 1)
player.tab.living_checkboxhaving = QtWidgets.QCheckBox(player.tab.gridLayoutWidget_5)
player.tab.living_checkboxhaving.setObjectName("living_checkboxhaving")
player.tab.gridLayout_5.addWidget(player.tab.living_checkboxhaving, 4, 4, 1, 1)
player.tab.line_135 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_135.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_135.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_135.setObjectName("line_135")
player.tab.gridLayout_5.addWidget(player.tab.line_135, 5, 2, 1, 1)
player.tab.line_136 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_136.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_136.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_136.setObjectName("line_136")
player.tab.gridLayout_5.addWidget(player.tab.line_136, 1, 4, 1, 1)
player.tab.living_labl = QtWidgets.QLabel(player.tab.gridLayoutWidget_5)
player.tab.living_labl.setObjectName("living_labl")
player.tab.gridLayout_5.addWidget(player.tab.living_labl, 4, 0, 1, 1)
player.tab.line_137 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_137.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_137.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_137.setObjectName("line_137")
player.tab.gridLayout_5.addWidget(player.tab.line_137, 12, 3, 1, 1)
player.tab.line_138 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_138.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_138.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_138.setObjectName("line_138")
player.tab.gridLayout_5.addWidget(player.tab.line_138, 0, 5, 1, 1)
player.tab.line_139 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_139.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_139.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_139.setObjectName("line_139")
player.tab.gridLayout_5.addWidget(player.tab.line_139, 3, 6, 1, 1)
player.tab.line_140 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_140.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_140.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_140.setObjectName("line_140")
player.tab.gridLayout_5.addWidget(player.tab.line_140, 1, 0, 1, 1)
player.tab.living_checkbox = QtWidgets.QCheckBox(player.tab.gridLayoutWidget_5)
player.tab.living_checkbox.setObjectName("living_checkbox")
player.tab.gridLayout_5.addWidget(player.tab.living_checkbox, 4, 2, 1, 1)
player.tab.line_141 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_141.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_141.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_141.setObjectName("line_141")
player.tab.gridLayout_5.addWidget(player.tab.line_141, 1, 3, 1, 1)
player.tab.line_142 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_142.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_142.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_142.setObjectName("line_142")
player.tab.gridLayout_5.addWidget(player.tab.line_142, 0, 1, 1, 1)
player.tab.line_143 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_143.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_143.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_143.setObjectName("line_143")
player.tab.gridLayout_5.addWidget(player.tab.line_143, 7, 0, 1, 1)
player.tab.line_144 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_144.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_144.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_144.setObjectName("line_144")
player.tab.gridLayout_5.addWidget(player.tab.line_144, 1, 5, 1, 1)
player.tab.line_145 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_145.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_145.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_145.setObjectName("line_145")
player.tab.gridLayout_5.addWidget(player.tab.line_145, 12, 1, 1, 1)
player.tab.line_146 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_146.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_146.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_146.setObjectName("line_146")
player.tab.gridLayout_5.addWidget(player.tab.line_146, 5, 0, 1, 1)
player.tab.medicine_checkbox = QtWidgets.QCheckBox(player.tab.gridLayoutWidget_5)
player.tab.medicine_checkbox.setObjectName("medicine_checkbox")
player.tab.gridLayout_5.addWidget(player.tab.medicine_checkbox, 6, 2, 1, 1)
player.tab.line_147 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_147.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_147.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_147.setObjectName("line_147")
player.tab.gridLayout_5.addWidget(player.tab.line_147, 13, 6, 1, 1)
player.tab.line_148 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_148.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_148.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_148.setObjectName("line_148")
player.tab.gridLayout_5.addWidget(player.tab.line_148, 13, 2, 1, 1)
player.tab.mindfulness_checkbox = QtWidgets.QCheckBox(player.tab.gridLayoutWidget_5)
player.tab.mindfulness_checkbox.setObjectName("mindfulness_checkbox")
player.tab.gridLayout_5.addWidget(player.tab.mindfulness_checkbox, 2, 2, 1, 1)
player.tab.line_149 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_149.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_149.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_149.setObjectName("line_149")
player.tab.gridLayout_5.addWidget(player.tab.line_149, 3, 2, 1, 1)
player.tab.line_150 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_150.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_150.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_150.setObjectName("line_150")
player.tab.gridLayout_5.addWidget(player.tab.line_150, 3, 5, 1, 1)
player.tab.medicine_checkboxhaving = QtWidgets.QCheckBox(player.tab.gridLayoutWidget_5)
player.tab.medicine_checkboxhaving.setObjectName("medicine_checkboxhaving")
player.tab.gridLayout_5.addWidget(player.tab.medicine_checkboxhaving, 6, 4, 1, 1)
player.tab.line_151 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_151.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_151.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_151.setObjectName("line_151")
player.tab.gridLayout_5.addWidget(player.tab.line_151, 1, 2, 1, 1)
player.tab.line_152 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_152.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_152.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_152.setObjectName("line_152")
player.tab.gridLayout_5.addWidget(player.tab.line_152, 13, 3, 1, 1)
player.tab.line_153 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_153.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_153.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_153.setObjectName("line_153")
player.tab.gridLayout_5.addWidget(player.tab.line_153, 7, 2, 1, 1)
player.tab.line_154 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_154.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_154.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_154.setObjectName("line_154")
player.tab.gridLayout_5.addWidget(player.tab.line_154, 13, 4, 1, 1)
player.tab.line_155 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_155.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_155.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_155.setObjectName("line_155")
player.tab.gridLayout_5.addWidget(player.tab.line_155, 7, 6, 1, 1)
player.tab.line_156 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_156.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_156.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_156.setObjectName("line_156")
player.tab.gridLayout_5.addWidget(player.tab.line_156, 13, 0, 1, 1)
player.tab.line_157 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_157.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_157.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_157.setObjectName("line_157")
player.tab.gridLayout_5.addWidget(player.tab.line_157, 3, 3, 1, 1)
player.tab.mindfulness_labl = QtWidgets.QLabel(player.tab.gridLayoutWidget_5)
player.tab.mindfulness_labl.setObjectName("mindfulness_labl")
player.tab.gridLayout_5.addWidget(player.tab.mindfulness_labl, 2, 0, 1, 1)
player.tab.line_158 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_158.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_158.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_158.setObjectName("line_158")
player.tab.gridLayout_5.addWidget(player.tab.line_158, 7, 4, 1, 1)
player.tab.save_giving_wise_checkboxhaving = QtWidgets.QCheckBox(player.tab.gridLayoutWidget_5)
player.tab.save_giving_wise_checkboxhaving.setObjectName("save_giving_wise_checkboxhaving")
player.tab.gridLayout_5.addWidget(player.tab.save_giving_wise_checkboxhaving, 12, 4, 1, 1)
player.tab.insight_labl = QtWidgets.QLabel(player.tab.gridLayoutWidget_5)
player.tab.insight_labl.setObjectName("insight_labl")
player.tab.gridLayout_5.addWidget(player.tab.insight_labl, 8, 0, 1, 1)
player.tab.line_159 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_159.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_159.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_159.setObjectName("line_159")
player.tab.gridLayout_5.addWidget(player.tab.line_159, 5, 4, 1, 1)
player.tab.medicine_labl = QtWidgets.QLabel(player.tab.gridLayoutWidget_5)
player.tab.medicine_labl.setObjectName("medicine_labl")
player.tab.gridLayout_5.addWidget(player.tab.medicine_labl, 6, 0, 1, 1)
player.tab.line_160 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_160.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_160.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_160.setObjectName("line_160")
player.tab.gridLayout_5.addWidget(player.tab.line_160, 2, 1, 1, 1)
player.tab.znachenie_wise_labl = QtWidgets.QLabel(player.tab.gridLayoutWidget_5)
player.tab.znachenie_wise_labl.setObjectName("znachenie_wise_labl")
player.tab.gridLayout_5.addWidget(player.tab.znachenie_wise_labl, 0, 0, 1, 1)
player.tab.line_161 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_161.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_161.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_161.setObjectName("line_161")
player.tab.gridLayout_5.addWidget(player.tab.line_161, 13, 5, 1, 1)
player.tab.line_162 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_162.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_162.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_162.setObjectName("line_162")
player.tab.gridLayout_5.addWidget(player.tab.line_162, 9, 0, 1, 1)
player.tab.line_163 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_163.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_163.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_163.setObjectName("line_163")
player.tab.gridLayout_5.addWidget(player.tab.line_163, 9, 2, 1, 1)
player.tab.line_164 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_164.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_164.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_164.setObjectName("line_164")
player.tab.gridLayout_5.addWidget(player.tab.line_164, 11, 2, 1, 1)
player.tab.line_165 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_165.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_165.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_165.setObjectName("line_165")
player.tab.gridLayout_5.addWidget(player.tab.line_165, 11, 4, 1, 1)
player.tab.line_166 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_166.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_166.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_166.setObjectName("line_166")
player.tab.gridLayout_5.addWidget(player.tab.line_166, 9, 4, 1, 1)
player.tab.line_167 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_167.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_167.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_167.setObjectName("line_167")
player.tab.gridLayout_5.addWidget(player.tab.line_167, 9, 6, 1, 1)
player.tab.line_168 = QtWidgets.QFrame(player.tab.gridLayoutWidget_5)
player.tab.line_168.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_168.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_168.setObjectName("line_168")
player.tab.gridLayout_5.addWidget(player.tab.line_168, 11, 6, 1, 1)
player.tab.insight_checkbox = QtWidgets.QCheckBox(player.tab.gridLayoutWidget_5)
player.tab.insight_checkbox.setObjectName("insight_checkbox")
player.tab.gridLayout_5.addWidget(player.tab.insight_checkbox, 8, 2, 1, 1)
player.tab.care_of_animal_checkbox = QtWidgets.QCheckBox(player.tab.gridLayoutWidget_5)
player.tab.care_of_animal_checkbox.setObjectName("care_of_animal_checkbox")
player.tab.gridLayout_5.addWidget(player.tab.care_of_animal_checkbox, 10, 2, 1, 1)
player.tab.insight_checkboxhaving = QtWidgets.QCheckBox(player.tab.gridLayoutWidget_5)
player.tab.insight_checkboxhaving.setObjectName("insight_checkboxhaving")
player.tab.gridLayout_5.addWidget(player.tab.insight_checkboxhaving, 8, 4, 1, 1)
player.tab.care_of_animal_checkboxhaving = QtWidgets.QCheckBox(player.tab.gridLayoutWidget_5)
player.tab.care_of_animal_checkboxhaving.setObjectName("care_of_animal_checkboxhaving")
player.tab.gridLayout_5.addWidget(player.tab.care_of_animal_checkboxhaving, 10, 4, 1, 1)
player.tab.insight_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_5)
player.tab.insight_field.setObjectName("insight_field")
player.tab.gridLayout_5.addWidget(player.tab.insight_field, 8, 6, 1, 1)
player.tab.care_of_animal_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_5)
player.tab.care_of_animal_field.setObjectName("care_of_animal_field")
player.tab.gridLayout_5.addWidget(player.tab.care_of_animal_field, 10, 6, 1, 1)
player.tab.description_wise_labl = QtWidgets.QLabel(player.tab.characteristics_wise)
player.tab.description_wise_labl.setGeometry(QtCore.QRect(10, 266, 311, 241))
player.tab.description_wise_labl.setTextFormat(QtCore.Qt.PlainText)
player.tab.description_wise_labl.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
player.tab.description_wise_labl.setObjectName("description_wise_labl")
player.tab.caractersistics.addTab(player.tab.characteristics_wise, "")
player.tab.characteristics_charisma = QtWidgets.QWidget()
player.tab.characteristics_charisma.setObjectName("characteristics_charisma")
player.tab.gridLayoutWidget_6 = QtWidgets.QWidget(player.tab.characteristics_charisma)
player.tab.gridLayoutWidget_6.setGeometry(QtCore.QRect(0, 0, 311, 221))
player.tab.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
player.tab.gridLayout_6 = QtWidgets.QGridLayout(player.tab.gridLayoutWidget_6)
player.tab.gridLayout_6.setContentsMargins(10, 0, 0, 0)
player.tab.gridLayout_6.setObjectName("gridLayout_6")
player.tab.mod_charisma_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_6)
player.tab.mod_charisma_field.setObjectName("mod_charisma_field")
player.tab.gridLayout_6.addWidget(player.tab.mod_charisma_field, 0, 6, 1, 1)
player.tab.line_178 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_178.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_178.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_178.setObjectName("line_178")
player.tab.gridLayout_6.addWidget(player.tab.line_178, 1, 2, 1, 1)
player.tab.line_180 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_180.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_180.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_180.setObjectName("line_180")
player.tab.gridLayout_6.addWidget(player.tab.line_180, 10, 1, 1, 1)
player.tab.line_190 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_190.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_190.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_190.setObjectName("line_190")
player.tab.gridLayout_6.addWidget(player.tab.line_190, 1, 6, 1, 1)
player.tab.perfomance_checkboxhaving = QtWidgets.QCheckBox(player.tab.gridLayoutWidget_6)
player.tab.perfomance_checkboxhaving.setObjectName("perfomance_checkboxhaving")
player.tab.gridLayout_6.addWidget(player.tab.perfomance_checkboxhaving, 2, 4, 1, 1)
player.tab.line_183 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_183.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_183.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_183.setObjectName("line_183")
player.tab.gridLayout_6.addWidget(player.tab.line_183, 11, 6, 1, 1)
player.tab.line_185 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_185.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_185.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_185.setObjectName("line_185")
player.tab.gridLayout_6.addWidget(player.tab.line_185, 2, 5, 1, 1)
player.tab.line_176 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_176.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_176.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_176.setObjectName("line_176")
player.tab.gridLayout_6.addWidget(player.tab.line_176, 5, 6, 1, 1)
player.tab.line_206 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_206.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_206.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_206.setObjectName("line_206")
player.tab.gridLayout_6.addWidget(player.tab.line_206, 1, 1, 1, 1)
player.tab.line_194 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_194.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_194.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_194.setObjectName("line_194")
player.tab.gridLayout_6.addWidget(player.tab.line_194, 5, 4, 1, 1)
player.tab.save_giving_charisma_labl = QtWidgets.QLabel(player.tab.gridLayoutWidget_6)
player.tab.save_giving_charisma_labl.setObjectName("save_giving_charisma_labl")
player.tab.gridLayout_6.addWidget(player.tab.save_giving_charisma_labl, 10, 0, 1, 1)
player.tab.bullying_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_6)
player.tab.bullying_field.setObjectName("bullying_field")
player.tab.gridLayout_6.addWidget(player.tab.bullying_field, 4, 6, 1, 1)
player.tab.line_193 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_193.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_193.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_193.setObjectName("line_193")
player.tab.gridLayout_6.addWidget(player.tab.line_193, 5, 0, 1, 1)
player.tab.bullying_checkboxhaving = QtWidgets.QCheckBox(player.tab.gridLayoutWidget_6)
player.tab.bullying_checkboxhaving.setObjectName("bullying_checkboxhaving")
player.tab.gridLayout_6.addWidget(player.tab.bullying_checkboxhaving, 4, 4, 1, 1)
player.tab.line_179 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_179.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_179.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_179.setObjectName("line_179")
player.tab.gridLayout_6.addWidget(player.tab.line_179, 3, 6, 1, 1)
player.tab.znachenie_charisma_labl = QtWidgets.QLabel(player.tab.gridLayoutWidget_6)
player.tab.znachenie_charisma_labl.setObjectName("znachenie_charisma_labl")
player.tab.gridLayout_6.addWidget(player.tab.znachenie_charisma_labl, 0, 0, 1, 1)
player.tab.line_174 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_174.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_174.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_174.setObjectName("line_174")
player.tab.gridLayout_6.addWidget(player.tab.line_174, 9, 2, 1, 1)
player.tab.line_188 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_188.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_188.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_188.setObjectName("line_188")
player.tab.gridLayout_6.addWidget(player.tab.line_188, 10, 3, 1, 1)
player.tab.perfomance_checkbox = QtWidgets.QCheckBox(player.tab.gridLayoutWidget_6)
player.tab.perfomance_checkbox.setObjectName("perfomance_checkbox")
player.tab.gridLayout_6.addWidget(player.tab.perfomance_checkbox, 2, 2, 1, 1)
player.tab.line_198 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_198.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_198.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_198.setObjectName("line_198")
player.tab.gridLayout_6.addWidget(player.tab.line_198, 9, 4, 1, 1)
player.tab.line_171 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_171.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_171.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_171.setObjectName("line_171")
player.tab.gridLayout_6.addWidget(player.tab.line_171, 1, 0, 1, 1)
player.tab.line_175 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_175.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_175.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_175.setObjectName("line_175")
player.tab.gridLayout_6.addWidget(player.tab.line_175, 9, 6, 1, 1)
player.tab.line_173 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_173.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_173.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_173.setObjectName("line_173")
player.tab.gridLayout_6.addWidget(player.tab.line_173, 11, 1, 1, 1)
player.tab.line_203 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_203.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_203.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_203.setObjectName("line_203")
player.tab.gridLayout_6.addWidget(player.tab.line_203, 11, 3, 1, 1)
player.tab.fraud_checkbox = QtWidgets.QCheckBox(player.tab.gridLayoutWidget_6)
player.tab.fraud_checkbox.setObjectName("fraud_checkbox")
player.tab.gridLayout_6.addWidget(player.tab.fraud_checkbox, 6, 2, 1, 1)
player.tab.fraud_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_6)
player.tab.fraud_field.setObjectName("fraud_field")
player.tab.gridLayout_6.addWidget(player.tab.fraud_field, 6, 6, 1, 1)
player.tab.line_201 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_201.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_201.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_201.setObjectName("line_201")
player.tab.gridLayout_6.addWidget(player.tab.line_201, 3, 4, 1, 1)
player.tab.line_205 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_205.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_205.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_205.setObjectName("line_205")
player.tab.gridLayout_6.addWidget(player.tab.line_205, 3, 5, 1, 1)
player.tab.line_195 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_195.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_195.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_195.setObjectName("line_195")
player.tab.gridLayout_6.addWidget(player.tab.line_195, 11, 2, 1, 1)
player.tab.line_170 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_170.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_170.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_170.setObjectName("line_170")
player.tab.gridLayout_6.addWidget(player.tab.line_170, 5, 2, 1, 1)
player.tab.line_181 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_181.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_181.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_181.setObjectName("line_181")
player.tab.gridLayout_6.addWidget(player.tab.line_181, 2, 1, 1, 1)
player.tab.line_196 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_196.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_196.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_196.setObjectName("line_196")
player.tab.gridLayout_6.addWidget(player.tab.line_196, 1, 3, 1, 1)
player.tab.line_197 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_197.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_197.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_197.setObjectName("line_197")
player.tab.gridLayout_6.addWidget(player.tab.line_197, 3, 0, 1, 1)
player.tab.znachenie_charisma_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_6)
player.tab.znachenie_charisma_field.setObjectName("znachenie_charisma_field")
player.tab.gridLayout_6.addWidget(player.tab.znachenie_charisma_field, 0, 2, 1, 1)
player.tab.save_giving_charisma_checkboxhaving = QtWidgets.QCheckBox(player.tab.gridLayoutWidget_6)
player.tab.save_giving_charisma_checkboxhaving.setObjectName("save_giving_charisma_checkboxhaving")
player.tab.gridLayout_6.addWidget(player.tab.save_giving_charisma_checkboxhaving, 10, 4, 1, 1)
player.tab.line_204 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_204.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_204.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_204.setObjectName("line_204")
player.tab.gridLayout_6.addWidget(player.tab.line_204, 11, 5, 1, 1)
player.tab.fraud_checkboxhaving = QtWidgets.QCheckBox(player.tab.gridLayoutWidget_6)
player.tab.fraud_checkboxhaving.setObjectName("fraud_checkboxhaving")
player.tab.gridLayout_6.addWidget(player.tab.fraud_checkboxhaving, 6, 4, 1, 1)
player.tab.line_184 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_184.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_184.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_184.setObjectName("line_184")
player.tab.gridLayout_6.addWidget(player.tab.line_184, 3, 1, 1, 1)
player.tab.line_172 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_172.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_172.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_172.setObjectName("line_172")
player.tab.gridLayout_6.addWidget(player.tab.line_172, 10, 5, 1, 1)
player.tab.line_199 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_199.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_199.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_199.setObjectName("line_199")
player.tab.gridLayout_6.addWidget(player.tab.line_199, 0, 1, 1, 1)
player.tab.line_202 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_202.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_202.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_202.setObjectName("line_202")
player.tab.gridLayout_6.addWidget(player.tab.line_202, 1, 4, 1, 1)
player.tab.line_191 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_191.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_191.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_191.setObjectName("line_191")
player.tab.gridLayout_6.addWidget(player.tab.line_191, 3, 3, 1, 1)
player.tab.bullying_checkbox = QtWidgets.QCheckBox(player.tab.gridLayoutWidget_6)
player.tab.bullying_checkbox.setObjectName("bullying_checkbox")
player.tab.gridLayout_6.addWidget(player.tab.bullying_checkbox, 4, 2, 1, 1)
