
player.tab.mod_charisma_labl = QtWidgets.QLabel(player.tab.gridLayoutWidget_6)
player.tab.mod_charisma_labl.setObjectName("mod_charisma_labl")
player.tab.gridLayout_6.addWidget(player.tab.mod_charisma_labl, 0, 4, 1, 1)
player.tab.bullying_labl = QtWidgets.QLabel(player.tab.gridLayoutWidget_6)
player.tab.bullying_labl.setObjectName("bullying_labl")
player.tab.gridLayout_6.addWidget(player.tab.bullying_labl, 4, 0, 1, 1)
player.tab.line_186 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_186.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_186.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_186.setObjectName("line_186")
player.tab.gridLayout_6.addWidget(player.tab.line_186, 0, 3, 1, 1)
player.tab.line_169 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_169.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_169.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_169.setObjectName("line_169")
player.tab.gridLayout_6.addWidget(player.tab.line_169, 11, 4, 1, 1)
player.tab.perfomance_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_6)
player.tab.perfomance_field.setObjectName("perfomance_field")
player.tab.gridLayout_6.addWidget(player.tab.perfomance_field, 2, 6, 1, 1)
player.tab.conviction_labl = QtWidgets.QLabel(player.tab.gridLayoutWidget_6)
player.tab.conviction_labl.setObjectName("conviction_labl")
player.tab.gridLayout_6.addWidget(player.tab.conviction_labl, 8, 0, 1, 1)
player.tab.line_189 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_189.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_189.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_189.setObjectName("line_189")
player.tab.gridLayout_6.addWidget(player.tab.line_189, 3, 2, 1, 1)
player.tab.performance_labl = QtWidgets.QLabel(player.tab.gridLayoutWidget_6)
player.tab.performance_labl.setObjectName("performance_labl")
player.tab.gridLayout_6.addWidget(player.tab.performance_labl, 2, 0, 1, 1)
player.tab.line_182 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_182.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_182.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_182.setObjectName("line_182")
player.tab.gridLayout_6.addWidget(player.tab.line_182, 11, 0, 1, 1)
player.tab.line_200 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_200.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_200.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_200.setObjectName("line_200")
player.tab.gridLayout_6.addWidget(player.tab.line_200, 2, 3, 1, 1)
player.tab.line_177 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_177.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_177.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_177.setObjectName("line_177")
player.tab.gridLayout_6.addWidget(player.tab.line_177, 1, 5, 1, 1)
player.tab.line_187 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_187.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_187.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_187.setObjectName("line_187")
player.tab.gridLayout_6.addWidget(player.tab.line_187, 9, 0, 1, 1)
player.tab.fraud_labl = QtWidgets.QLabel(player.tab.gridLayoutWidget_6)
player.tab.fraud_labl.setObjectName("fraud_labl")
player.tab.gridLayout_6.addWidget(player.tab.fraud_labl, 6, 0, 1, 1)
player.tab.line_192 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_192.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_192.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_192.setObjectName("line_192")
player.tab.gridLayout_6.addWidget(player.tab.line_192, 0, 5, 1, 1)
player.tab.line_207 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_207.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_207.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_207.setObjectName("line_207")
player.tab.gridLayout_6.addWidget(player.tab.line_207, 7, 0, 1, 1)
player.tab.line_208 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_208.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_208.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_208.setObjectName("line_208")
player.tab.gridLayout_6.addWidget(player.tab.line_208, 7, 2, 1, 1)
player.tab.line_209 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_209.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_209.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_209.setObjectName("line_209")
player.tab.gridLayout_6.addWidget(player.tab.line_209, 7, 4, 1, 1)
player.tab.line_210 = QtWidgets.QFrame(player.tab.gridLayoutWidget_6)
player.tab.line_210.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_210.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_210.setObjectName("line_210")
player.tab.gridLayout_6.addWidget(player.tab.line_210, 7, 6, 1, 1)
player.tab.conviction_checkbox = QtWidgets.QCheckBox(player.tab.gridLayoutWidget_6)
player.tab.conviction_checkbox.setObjectName("conviction_checkbox")
player.tab.gridLayout_6.addWidget(player.tab.conviction_checkbox, 8, 2, 1, 1)
player.tab.conviction_checkboxhaving = QtWidgets.QCheckBox(player.tab.gridLayoutWidget_6)
player.tab.conviction_checkboxhaving.setObjectName("conviction_checkboxhaving")
player.tab.gridLayout_6.addWidget(player.tab.conviction_checkboxhaving, 8, 4, 1, 1)
player.tab.conviction_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_6)
player.tab.conviction_field.setObjectName("conviction_field")
player.tab.gridLayout_6.addWidget(player.tab.conviction_field, 8, 6, 1, 1)
player.tab.description_charisma_labl = QtWidgets.QLabel(player.tab.characteristics_charisma)
player.tab.description_charisma_labl.setGeometry(QtCore.QRect(10, 230, 301, 221))
player.tab.description_charisma_labl.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
player.tab.description_charisma_labl.setProperty("123", "")
player.tab.description_charisma_labl.setObjectName("description_charisma_labl")
player.tab.caractersistics.addTab(player.tab.characteristics_charisma, "")
player.tab.person_name = QtWidgets.QLabel(player.tab)
player.tab.person_name.setGeometry(QtCore.QRect(10, 10, 241, 41))
font = QtGui.QFont()
font.setPointSize(25)
player.tab.person_name.setFont(font)
player.tab.person_name.setObjectName("person_name")
player.tab.description_person = QtWidgets.QToolBox(player.tab)
player.tab.description_person.setGeometry(QtCore.QRect(0, 60, 341, 331))
font = QtGui.QFont()
font.setPointSize(9)
player.tab.description_person.setFont(font)
player.tab.description_person.setObjectName("description_person")
player.tab.page_1 = QtWidgets.QWidget()
player.tab.page_1.setGeometry(QtCore.QRect(0, 0, 341, 135))
player.tab.page_1.setObjectName("page_1")
player.tab.description_of_person_1 = QtWidgets.QTextEdit(player.tab.page_1)
player.tab.description_of_person_1.setGeometry(QtCore.QRect(0, 0, 341, 141))
player.tab.description_of_person_1.setObjectName("description_of_person_1")
player.tab.description_person.addItem(player.tab.page_1, "")
player.tab.page_2 = QtWidgets.QWidget()
player.tab.page_2.setGeometry(QtCore.QRect(0, 0, 341, 135))
player.tab.page_2.setObjectName("page_2")
player.tab.description_of_person_2 = QtWidgets.QTextEdit(player.tab.page_2)
player.tab.description_of_person_2.setGeometry(QtCore.QRect(0, 0, 341, 141))
player.tab.description_of_person_2.setObjectName("description_of_person_2")
player.tab.description_person.addItem(player.tab.page_2, "")
player.tab.page_3 = QtWidgets.QWidget()
player.tab.page_3.setGeometry(QtCore.QRect(0, 0, 341, 135))
player.tab.page_3.setObjectName("page_3")
player.tab.description_of_person_3 = QtWidgets.QTextEdit(player.tab.page_3)
player.tab.description_of_person_3.setGeometry(QtCore.QRect(0, 0, 341, 141))
player.tab.description_of_person_3.setObjectName("description_of_person_3")
player.tab.description_person.addItem(player.tab.page_3, "")
player.tab.page_4 = QtWidgets.QWidget()
player.tab.page_4.setGeometry(QtCore.QRect(0, 0, 341, 135))
player.tab.page_4.setObjectName("page_4")
player.tab.description_of_person_4 = QtWidgets.QTextEdit(player.tab.page_4)
player.tab.description_of_person_4.setGeometry(QtCore.QRect(0, 0, 341, 141))
player.tab.description_of_person_4.setObjectName("description_of_person_4")
player.tab.description_person.addItem(player.tab.page_4, "")
player.tab.page_5 = QtWidgets.QWidget()
player.tab.page_5.setGeometry(QtCore.QRect(0, 0, 341, 135))
player.tab.page_5.setObjectName("page_5")
player.tab.description_of_person_5 = QtWidgets.QTextEdit(player.tab.page_5)
player.tab.description_of_person_5.setGeometry(QtCore.QRect(0, 0, 341, 141))
player.tab.description_of_person_5.setObjectName("description_of_person_5")
player.tab.description_person.addItem(player.tab.page_5, "")
player.tab.page_6 = QtWidgets.QWidget()
player.tab.page_6.setGeometry(QtCore.QRect(0, 0, 341, 135))
player.tab.page_6.setObjectName("page_6")
player.tab.description_of_person_6 = QtWidgets.QTextEdit(player.tab.page_6)
player.tab.description_of_person_6.setGeometry(QtCore.QRect(0, 0, 341, 141))
player.tab.description_of_person_6.setObjectName("description_of_person_6")
player.tab.description_person.addItem(player.tab.page_6, "")
player.tab.page_7 = QtWidgets.QWidget()
player.tab.page_7.setGeometry(QtCore.QRect(0, 0, 341, 135))
player.tab.page_7.setObjectName("page_7")
player.tab.description_of_person_7 = QtWidgets.QTextEdit(player.tab.page_7)
player.tab.description_of_person_7.setGeometry(QtCore.QRect(0, 0, 341, 141))
player.tab.description_of_person_7.setObjectName("description_of_person_7")
player.tab.description_person.addItem(player.tab.page_7, "")
player.tab.magic_list = QtWidgets.QTabWidget(player.tab)
player.tab.magic_list.setGeometry(QtCore.QRect(340, 400, 331, 461))
font = QtGui.QFont()
font.setPointSize(9)
player.tab.magic_list.setFont(font)
player.tab.magic_list.setTabPosition(QtWidgets.QTabWidget.West)
player.tab.magic_list.setTabShape(QtWidgets.QTabWidget.Rounded)
player.tab.magic_list.setElideMode(QtCore.Qt.ElideLeft)
player.tab.magic_list.setTabBarAutoHide(False)
player.tab.magic_list.setObjectName("magic_list")
player.tab.mag_lvl0 = QtWidgets.QWidget()
player.tab.mag_lvl0.setObjectName("mag_lvl0")
player.tab.list_mag_lvl0 = QtWidgets.QListWidget(player.tab.mag_lvl0)
player.tab.list_mag_lvl0.setGeometry(QtCore.QRect(0, 0, 301, 451))
player.tab.list_mag_lvl0.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
player.tab.list_mag_lvl0.setProperty("showDropIndicator", False)
player.tab.list_mag_lvl0.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
player.tab.list_mag_lvl0.setDefaultDropAction(QtCore.Qt.MoveAction)
player.tab.list_mag_lvl0.setAlternatingRowColors(False)
player.tab.list_mag_lvl0.setMovement(QtWidgets.QListView.Free)
player.tab.list_mag_lvl0.setObjectName("list_mag_lvl0")
player.tab.magic_list.addTab(player.tab.mag_lvl0, "")
player.tab.mag_lvl1 = QtWidgets.QWidget()
player.tab.mag_lvl1.setObjectName("mag_lvl1")
player.tab.list_mag_lvl1 = QtWidgets.QListWidget(player.tab.mag_lvl1)
player.tab.list_mag_lvl1.setGeometry(QtCore.QRect(0, 0, 301, 451))
player.tab.list_mag_lvl1.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
player.tab.list_mag_lvl1.setProperty("showDropIndicator", False)
player.tab.list_mag_lvl1.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
player.tab.list_mag_lvl1.setDefaultDropAction(QtCore.Qt.MoveAction)
player.tab.list_mag_lvl1.setAlternatingRowColors(False)
player.tab.list_mag_lvl1.setMovement(QtWidgets.QListView.Free)
player.tab.list_mag_lvl1.setObjectName("list_mag_lvl1")
player.tab.magic_list.addTab(player.tab.mag_lvl1, "")
player.tab.mag_lvl2 = QtWidgets.QWidget()
player.tab.mag_lvl2.setObjectName("mag_lvl2")
player.tab.list_mag_lvl2 = QtWidgets.QListWidget(player.tab.mag_lvl2)
player.tab.list_mag_lvl2.setGeometry(QtCore.QRect(0, 0, 301, 451))
player.tab.list_mag_lvl2.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
player.tab.list_mag_lvl2.setProperty("showDropIndicator", False)
player.tab.list_mag_lvl2.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
player.tab.list_mag_lvl2.setDefaultDropAction(QtCore.Qt.MoveAction)
player.tab.list_mag_lvl2.setAlternatingRowColors(False)
player.tab.list_mag_lvl2.setMovement(QtWidgets.QListView.Free)
player.tab.list_mag_lvl2.setObjectName("list_mag_lvl2")
player.tab.magic_list.addTab(player.tab.mag_lvl2, "")
player.tab.mag_lvl3 = QtWidgets.QWidget()
player.tab.mag_lvl3.setObjectName("mag_lvl3")
player.tab.list_mag_lvl3 = QtWidgets.QListWidget(player.tab.mag_lvl3)
player.tab.list_mag_lvl3.setGeometry(QtCore.QRect(0, 0, 301, 451))
player.tab.list_mag_lvl3.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
player.tab.list_mag_lvl3.setProperty("showDropIndicator", False)
player.tab.list_mag_lvl3.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
player.tab.list_mag_lvl3.setDefaultDropAction(QtCore.Qt.MoveAction)
player.tab.list_mag_lvl3.setAlternatingRowColors(False)
player.tab.list_mag_lvl3.setMovement(QtWidgets.QListView.Free)
player.tab.list_mag_lvl3.setObjectName("list_mag_lvl3")
player.tab.magic_list.addTab(player.tab.mag_lvl3, "")
player.tab.mag_lvl4 = QtWidgets.QWidget()
player.tab.mag_lvl4.setObjectName("mag_lvl4")
player.tab.list_mag_lvl4 = QtWidgets.QListWidget(player.tab.mag_lvl4)
player.tab.list_mag_lvl4.setGeometry(QtCore.QRect(0, 0, 301, 451))
player.tab.list_mag_lvl4.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
player.tab.list_mag_lvl4.setProperty("showDropIndicator", False)
player.tab.list_mag_lvl4.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
player.tab.list_mag_lvl4.setDefaultDropAction(QtCore.Qt.MoveAction)
player.tab.list_mag_lvl4.setAlternatingRowColors(False)
player.tab.list_mag_lvl4.setMovement(QtWidgets.QListView.Free)
player.tab.list_mag_lvl4.setObjectName("list_mag_lvl4")
player.tab.magic_list.addTab(player.tab.mag_lvl4, "")
player.tab.mag_lvl5 = QtWidgets.QWidget()
player.tab.mag_lvl5.setObjectName("mag_lvl5")
player.tab.list_mag_lvl5 = QtWidgets.QListWidget(player.tab.mag_lvl5)
player.tab.list_mag_lvl5.setGeometry(QtCore.QRect(0, 0, 301, 451))
player.tab.list_mag_lvl5.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
player.tab.list_mag_lvl5.setProperty("showDropIndicator", False)
player.tab.list_mag_lvl5.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
player.tab.list_mag_lvl5.setDefaultDropAction(QtCore.Qt.MoveAction)
player.tab.list_mag_lvl5.setAlternatingRowColors(False)
player.tab.list_mag_lvl5.setMovement(QtWidgets.QListView.Free)
player.tab.list_mag_lvl5.setObjectName("list_mag_lvl5")
player.tab.magic_list.addTab(player.tab.mag_lvl5, "")
player.tab.mag_lvl6 = QtWidgets.QWidget()
player.tab.mag_lvl6.setObjectName("mag_lvl6")
player.tab.list_mag_lvl6 = QtWidgets.QListWidget(player.tab.mag_lvl6)
player.tab.list_mag_lvl6.setGeometry(QtCore.QRect(0, 0, 301, 451))
player.tab.list_mag_lvl6.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
player.tab.list_mag_lvl6.setProperty("showDropIndicator", False)
player.tab.list_mag_lvl6.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
player.tab.list_mag_lvl6.setDefaultDropAction(QtCore.Qt.MoveAction)
player.tab.list_mag_lvl6.setAlternatingRowColors(False)
player.tab.list_mag_lvl6.setMovement(QtWidgets.QListView.Free)
player.tab.list_mag_lvl6.setObjectName("list_mag_lvl6")
player.tab.magic_list.addTab(player.tab.mag_lvl6, "")
player.tab.mag_lvl7 = QtWidgets.QWidget()
player.tab.mag_lvl7.setObjectName("mag_lvl7")
player.tab.list_mag_lvl7 = QtWidgets.QListWidget(player.tab.mag_lvl7)
player.tab.list_mag_lvl7.setGeometry(QtCore.QRect(0, 0, 301, 451))
player.tab.list_mag_lvl7.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
player.tab.list_mag_lvl7.setProperty("showDropIndicator", False)
player.tab.list_mag_lvl7.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
player.tab.list_mag_lvl7.setDefaultDropAction(QtCore.Qt.MoveAction)
player.tab.list_mag_lvl7.setAlternatingRowColors(False)
player.tab.list_mag_lvl7.setMovement(QtWidgets.QListView.Free)
player.tab.list_mag_lvl7.setObjectName("list_mag_lvl7")
player.tab.magic_list.addTab(player.tab.mag_lvl7, "")
player.tab.mag_lvl8 = QtWidgets.QWidget()
player.tab.mag_lvl8.setObjectName("mag_lvl8")
player.tab.list_mag_lvl8 = QtWidgets.QListWidget(player.tab.mag_lvl8)
player.tab.list_mag_lvl8.setGeometry(QtCore.QRect(0, 0, 301, 451))
player.tab.list_mag_lvl8.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
player.tab.list_mag_lvl8.setProperty("showDropIndicator", False)
player.tab.list_mag_lvl8.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
player.tab.list_mag_lvl8.setDefaultDropAction(QtCore.Qt.MoveAction)
player.tab.list_mag_lvl8.setAlternatingRowColors(False)
player.tab.list_mag_lvl8.setMovement(QtWidgets.QListView.Free)
player.tab.list_mag_lvl8.setObjectName("list_mag_lvl8")
player.tab.magic_list.addTab(player.tab.mag_lvl8, "")
player.tab.mag_lvl9 = QtWidgets.QWidget()
player.tab.mag_lvl9.setObjectName("mag_lvl9")
player.tab.list_mag_lvl9 = QtWidgets.QListWidget(player.tab.mag_lvl9)
player.tab.list_mag_lvl9.setGeometry(QtCore.QRect(0, 0, 301, 451))
player.tab.list_mag_lvl9.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
player.tab.list_mag_lvl9.setProperty("showDropIndicator", False)
player.tab.list_mag_lvl9.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
player.tab.list_mag_lvl9.setDefaultDropAction(QtCore.Qt.MoveAction)
player.tab.list_mag_lvl9.setAlternatingRowColors(False)
player.tab.list_mag_lvl9.setMovement(QtWidgets.QListView.Free)
player.tab.list_mag_lvl9.setObjectName("list_mag_lvl9")
player.tab.magic_list.addTab(player.tab.mag_lvl9, "")
player.tab.much_inventories = QtWidgets.QTabWidget(player.tab)
player.tab.much_inventories.setGeometry(QtCore.QRect(790, 400, 311, 431))
font = QtGui.QFont()
font.setPointSize(9)
player.tab.much_inventories.setFont(font)
player.tab.much_inventories.setTabPosition(QtWidgets.QTabWidget.West)
player.tab.much_inventories.setTabShape(QtWidgets.QTabWidget.Rounded)
player.tab.much_inventories.setElideMode(QtCore.Qt.ElideLeft)
player.tab.much_inventories.setTabBarAutoHide(False)
player.tab.much_inventories.setObjectName("much_inventories")
player.tab.on_person_tab = QtWidgets.QWidget()
player.tab.on_person_tab.setObjectName("on_person_tab")
player.tab.on_person_list = QtWidgets.QListWidget(player.tab.on_person_tab)
player.tab.on_person_list.setGeometry(QtCore.QRect(0, 0, 281, 421))
player.tab.on_person_list.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
player.tab.on_person_list.setProperty("showDropIndicator", False)
player.tab.on_person_list.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
player.tab.on_person_list.setDefaultDropAction(QtCore.Qt.MoveAction)
player.tab.on_person_list.setAlternatingRowColors(False)
player.tab.on_person_list.setMovement(QtWidgets.QListView.Free)
player.tab.on_person_list.setObjectName("on_person_list")
player.tab.much_inventories.addTab(player.tab.on_person_tab, "")
player.tab.inventory_tab = QtWidgets.QWidget()
player.tab.inventory_tab.setObjectName("inventory_tab")
player.tab.in_inventory_list = QtWidgets.QListWidget(player.tab.inventory_tab)
player.tab.in_inventory_list.setGeometry(QtCore.QRect(0, 0, 281, 421))
player.tab.in_inventory_list.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
player.tab.in_inventory_list.setProperty("showDropIndicator", False)
player.tab.in_inventory_list.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
player.tab.in_inventory_list.setDefaultDropAction(QtCore.Qt.MoveAction)
player.tab.in_inventory_list.setAlternatingRowColors(False)
player.tab.in_inventory_list.setMovement(QtWidgets.QListView.Free)
player.tab.in_inventory_list.setObjectName("in_inventory_list")
player.tab.much_inventories.addTab(player.tab.inventory_tab, "")
player.tab.can_have_invent_tab = QtWidgets.QWidget()
player.tab.can_have_invent_tab.setObjectName("can_have_invent_tab")
player.tab.can_have_invent_list = QtWidgets.QListWidget(player.tab.can_have_invent_tab)
player.tab.can_have_invent_list.setGeometry(QtCore.QRect(0, 0, 281, 421))
player.tab.can_have_invent_list.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
player.tab.can_have_invent_list.setProperty("showDropIndicator", False)
player.tab.can_have_invent_list.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
player.tab.can_have_invent_list.setDefaultDropAction(QtCore.Qt.MoveAction)
player.tab.can_have_invent_list.setAlternatingRowColors(False)
player.tab.can_have_invent_list.setMovement(QtWidgets.QListView.Free)
player.tab.can_have_invent_list.setObjectName("can_have_invent_list")
player.tab.much_inventories.addTab(player.tab.can_have_invent_tab, "Умен, особ, владен.")
player.tab.spechial_invent_tab = QtWidgets.QWidget()
player.tab.spechial_invent_tab.setObjectName("spechial_invent_tab")
player.tab.spechial_invent_list = QtWidgets.QListWidget(player.tab.spechial_invent_tab)
player.tab.spechial_invent_list.setGeometry(QtCore.QRect(0, 0, 281, 421))
player.tab.spechial_invent_list.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
player.tab.spechial_invent_list.setProperty("showDropIndicator", False)
player.tab.spechial_invent_list.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
player.tab.spechial_invent_list.setDefaultDropAction(QtCore.Qt.MoveAction)
player.tab.spechial_invent_list.setAlternatingRowColors(False)
player.tab.spechial_invent_list.setMovement(QtWidgets.QListView.Free)
player.tab.spechial_invent_list.setObjectName("spechial_invent_list")
player.tab.much_inventories.addTab(player.tab.spechial_invent_tab, "")
player.tab.main_clock = QtWidgets.QDateTimeEdit(player.tab)
player.tab.main_clock.setGeometry(QtCore.QRect(990, 0, 101, 21))
font = QtGui.QFont()
font.setPointSize(9)
font.setKerning(True)
font.setStyleStrategy(QtGui.QFont.PreferAntialias)
player.tab.main_clock.setFont(font)
player.tab.main_clock.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
player.tab.main_clock.setKeyboardTracking(False)
player.tab.main_clock.setObjectName("main_clock")
player.tab.state_person = QtWidgets.QTabWidget(player.tab)
player.tab.state_person.setGeometry(QtCore.QRect(340, 60, 451, 341))
font = QtGui.QFont()
font.setPointSize(9)
player.tab.state_person.setFont(font)
player.tab.state_person.setObjectName("state_person")
player.tab_23 = QtWidgets.QWidget()
player.tab_23.setObjectName("tab_23")
player.tab.label_64 = QtWidgets.QLabel(player.tab_23)
player.tab.label_64.setGeometry(QtCore.QRect(46, 13, 47, 13))
font = QtGui.QFont()
font.setPointSize(9)
player.tab.label_64.setFont(font)
player.tab.label_64.setObjectName("label_64")
player.tab.label_65 = QtWidgets.QLabel(player.tab_23)
player.tab.label_65.setGeometry(QtCore.QRect(30, 40, 61, 16))
font = QtGui.QFont()
font.setPointSize(9)
player.tab.label_65.setFont(font)
player.tab.label_65.setObjectName("label_65")
player.tab.label_66 = QtWidgets.QLabel(player.tab_23)
player.tab.label_66.setGeometry(QtCore.QRect(53, 70, 47, 13))
font = QtGui.QFont()
font.setPointSize(9)
player.tab.label_66.setFont(font)
player.tab.label_66.setObjectName("label_66")
player.tab.label_68 = QtWidgets.QLabel(player.tab_23)
player.tab.label_68.setGeometry(QtCore.QRect(26, 100, 71, 16))
font = QtGui.QFont()
font.setPointSize(9)
player.tab.label_68.setFont(font)
player.tab.label_68.setObjectName("label_68")
player.tab.lvl_field = QtWidgets.QLineEdit(player.tab_23)
player.tab.lvl_field.setGeometry(QtCore.QRect(83, 40, 131, 20))
player.tab.lvl_field.setObjectName("lvl_field")
player.tab.speed_field = QtWidgets.QLineEdit(player.tab_23)
player.tab.speed_field.setGeometry(QtCore.QRect(84, 100, 131, 20))
player.tab.speed_field.setObjectName("speed_field")
player.tab.label_71 = QtWidgets.QLabel(player.tab_23)
player.tab.label_71.setGeometry(QtCore.QRect(10, 160, 71, 16))
font = QtGui.QFont()
font.setPointSize(9)
player.tab.label_71.setFont(font)
player.tab.label_71.setObjectName("label_71")
player.tab.kost_hitov_field = QtWidgets.QLineEdit(player.tab_23)
player.tab.kost_hitov_field.setGeometry(QtCore.QRect(83, 160, 111, 20))
player.tab.kost_hitov_field.setObjectName("kost_hitov_field")
player.tab.class_combobox = QtWidgets.QComboBox(player.tab_23)
player.tab.class_combobox.setGeometry(QtCore.QRect(83, 10, 131, 22))
player.tab.class_combobox.setObjectName("class_combobox")
player.tab.rase_combobox = QtWidgets.QComboBox(player.tab_23)
player.tab.rase_combobox.setGeometry(QtCore.QRect(83, 68, 131, 22))
player.tab.rase_combobox.setObjectName("rase_combobox")
player.tab.up_character_checkbox = QtWidgets.QCheckBox(player.tab_23)
player.tab.up_character_checkbox.setGeometry(QtCore.QRect(-2, 245, 101, 20))
font = QtGui.QFont()
font.setPointSize(9)
player.tab.up_character_checkbox.setFont(font)
player.tab.up_character_checkbox.setLayoutDirection(QtCore.Qt.RightToLeft)
player.tab.up_character_checkbox.setAutoFillBackground(False)
player.tab.up_character_checkbox.setAutoExclusive(False)
player.tab.up_character_checkbox.setTristate(False)
player.tab.up_character_checkbox.setObjectName("up_character_checkbox")
player.tab.label_73 = QtWidgets.QLabel(player.tab_23)
player.tab.label_73.setGeometry(QtCore.QRect(23, 211, 61, 31))
font = QtGui.QFont()
font.setPointSize(9)
player.tab.label_73.setFont(font)
player.tab.label_73.setObjectName("label_73")
player.tab.passwise_field = QtWidgets.QLineEdit(player.tab_23)
player.tab.passwise_field.setGeometry(QtCore.QRect(78, 220, 111, 20))
player.tab.passwise_field.setObjectName("passwise_field")
player.tab.label_47 = QtWidgets.QLabel(player.tab_23)
player.tab.label_47.setGeometry(QtCore.QRect(13, 130, 81, 16))
font = QtGui.QFont()
font.setPointSize(9)
player.tab.label_47.setFont(font)
player.tab.label_47.setObjectName("label_47")
player.tab.class_zakl_field = QtWidgets.QLineEdit(player.tab_23)
player.tab.class_zakl_field.setGeometry(QtCore.QRect(83, 130, 291, 20))
player.tab.class_zakl_field.setObjectName("class_zakl_field")
player.tab.label_48 = QtWidgets.QLabel(player.tab_23)
player.tab.label_48.setGeometry(QtCore.QRect(4, 190, 91, 16))
font = QtGui.QFont()
font.setPointSize(9)
player.tab.label_48.setFont(font)
player.tab.label_48.setObjectName("label_48")
player.tab.base_characteristics_field = QtWidgets.QLineEdit(player.tab_23)
player.tab.base_characteristics_field.setGeometry(QtCore.QRect(94, 190, 291, 20))
player.tab.base_characteristics_field.setObjectName("base_characteristics_field")
player.tab.state_person.addTab(player.tab_23, "")
player.tab_22 = QtWidgets.QWidget()
player.tab_22.setObjectName("tab_22")
player.tab.hp_labl = QtWidgets.QLabel(player.tab_22)
player.tab.hp_labl.setGeometry(QtCore.QRect(30, 10, 61, 20))
font = QtGui.QFont()
font.setPointSize(9)
player.tab.hp_labl.setFont(font)
player.tab.hp_labl.setObjectName("hp_labl")
player.tab.hp_at_this_moment_field = QtWidgets.QLineEdit(player.tab_22)
player.tab.hp_at_this_moment_field.setGeometry(QtCore.QRect(90, 10, 61, 20))
player.tab.hp_at_this_moment_field.setObjectName("hp_at_this_moment_field")
player.tab.label_45 = QtWidgets.QLabel(player.tab_22)
player.tab.label_45.setGeometry(QtCore.QRect(160, 10, 16, 16))
player.tab.label_45.setObjectName("label_45")
player.tab.hp_full_field = QtWidgets.QLineEdit(player.tab_22)
player.tab.hp_full_field.setGeometry(QtCore.QRect(170, 10, 61, 20))
player.tab.hp_full_field.setObjectName("hp_full_field")
player.tab.hp_prbar = QtWidgets.QProgressBar(player.tab_22)
player.tab.hp_prbar.setGeometry(QtCore.QRect(240, 10, 201, 21))
player.tab.hp_prbar.setStyleSheet("QProgressBar::chunk {\n"
"    background-color: red;\n"
"    text-align: center\n"
"}")
player.tab.hp_prbar.setProperty("value", 50)
player.tab.hp_prbar.setAlignment(QtCore.Qt.AlignCenter)
player.tab.hp_prbar.setTextVisible(True)
player.tab.hp_prbar.setOrientation(QtCore.Qt.Horizontal)
player.tab.hp_prbar.setInvertedAppearance(False)
player.tab.hp_prbar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
player.tab.hp_prbar.setObjectName("hp_prbar")
player.tab.initiative_labl = QtWidgets.QLabel(player.tab_22)
player.tab.initiative_labl.setGeometry(QtCore.QRect(18, 94, 71, 16))
font = QtGui.QFont()
font.setPointSize(9)
player.tab.initiative_labl.setFont(font)
player.tab.initiative_labl.setObjectName("initiative_labl")
player.tab.initiative_field = QtWidgets.QLineEdit(player.tab_22)
player.tab.initiative_field.setGeometry(QtCore.QRect(90, 94, 61, 20))
player.tab.initiative_field.setObjectName("initiative_field")
player.tab.sl_spas_labl = QtWidgets.QLabel(player.tab_22)
player.tab.sl_spas_labl.setGeometry(QtCore.QRect(14, 154, 81, 16))
font = QtGui.QFont()
font.setPointSize(9)
player.tab.sl_spas_labl.setFont(font)
player.tab.sl_spas_labl.setObjectName("sl_spas_labl")
player.tab.sl_spas_field = QtWidgets.QLineEdit(player.tab_22)
player.tab.sl_spas_field.setGeometry(QtCore.QRect(90, 154, 61, 20))
player.tab.sl_spas_field.setObjectName("sl_spas_field")
player.tab.bon_attack_labl = QtWidgets.QLabel(player.tab_22)
player.tab.bon_attack_labl.setGeometry(QtCore.QRect(26, 184, 61, 20))
font = QtGui.QFont()
font.setPointSize(9)
player.tab.bon_attack_labl.setFont(font)
player.tab.bon_attack_labl.setObjectName("bon_attack_labl")
player.tab.bon_attack_field = QtWidgets.QLineEdit(player.tab_22)
player.tab.bon_attack_field.setGeometry(QtCore.QRect(90, 184, 61, 20))
player.tab.bon_attack_field.setObjectName("bon_attack_field")
player.tab.save_giving_of_death = QtWidgets.QLabel(player.tab_22)
player.tab.save_giving_of_death.setGeometry(QtCore.QRect(4, 214, 81, 16))
font = QtGui.QFont()
font.setPointSize(9)
player.tab.save_giving_of_death.setFont(font)
player.tab.save_giving_of_death.setObjectName("save_giving_of_death")
player.tab.save_giving_of_death_success = QtWidgets.QLabel(player.tab_22)
player.tab.save_giving_of_death_success.setGeometry(QtCore.QRect(53, 238, 41, 16))
font = QtGui.QFont()
font.setPointSize(9)
player.tab.save_giving_of_death_success.setFont(font)
player.tab.save_giving_of_death_success.setObjectName("save_giving_of_death_success")
player.tab.save_giving_of_death_fail = QtWidgets.QLabel(player.tab_22)
player.tab.save_giving_of_death_fail.setGeometry(QtCore.QRect(46, 263, 47, 13))
font = QtGui.QFont()
font.setPointSize(9)
player.tab.save_giving_of_death_fail.setFont(font)
player.tab.save_giving_of_death_fail.setObjectName("save_giving_of_death_fail")
player.tab.save_giving_of_death_success_box_1 = QtWidgets.QCheckBox(player.tab_22)
player.tab.save_giving_of_death_success_box_1.setGeometry(QtCore.QRect(95, 238, 16, 17))
player.tab.save_giving_of_death_success_box_1.setText("")
player.tab.save_giving_of_death_success_box_1.setObjectName("save_giving_of_death_success_box_1")
player.tab.save_giving_of_death_success_box_2 = QtWidgets.QCheckBox(player.tab_22)
player.tab.save_giving_of_death_success_box_2.setGeometry(QtCore.QRect(115, 238, 16, 17))
player.tab.save_giving_of_death_success_box_2.setText("")
player.tab.save_giving_of_death_success_box_2.setObjectName("save_giving_of_death_success_box_2")
player.tab.save_giving_of_death_success_box_3 = QtWidgets.QCheckBox(player.tab_22)
player.tab.save_giving_of_death_success_box_3.setGeometry(QtCore.QRect(135, 238, 16, 17))
player.tab.save_giving_of_death_success_box_3.setText("")
player.tab.save_giving_of_death_success_box_3.setObjectName("save_giving_of_death_success_box_3")
player.tab.save_giving_of_death_fail_box_1 = QtWidgets.QCheckBox(player.tab_22)
player.tab.save_giving_of_death_fail_box_1.setGeometry(QtCore.QRect(95, 263, 16, 17))
player.tab.save_giving_of_death_fail_box_1.setText("")
player.tab.save_giving_of_death_fail_box_1.setObjectName("save_giving_of_death_fail_box_1")
player.tab.save_giving_of_death_fail_box_2 = QtWidgets.QCheckBox(player.tab_22)
player.tab.save_giving_of_death_fail_box_2.setGeometry(QtCore.QRect(115, 263, 16, 17))
player.tab.save_giving_of_death_fail_box_2.setText("")
player.tab.save_giving_of_death_fail_box_2.setObjectName("save_giving_of_death_fail_box_2")
player.tab.save_giving_of_death_fail_box_3 = QtWidgets.QCheckBox(player.tab_22)
player.tab.save_giving_of_death_fail_box_3.setGeometry(QtCore.QRect(135, 263, 16, 17))
player.tab.save_giving_of_death_fail_box_3.setText("")
player.tab.save_giving_of_death_fail_box_3.setObjectName("save_giving_of_death_fail_box_3")
player.tab.KD_labl = QtWidgets.QLabel(player.tab_22)
player.tab.KD_labl.setGeometry(QtCore.QRect(70, 124, 21, 16))
font = QtGui.QFont()
font.setPointSize(9)
player.tab.KD_labl.setFont(font)
player.tab.KD_labl.setObjectName("KD_labl")
player.tab.KD_field = QtWidgets.QLineEdit(player.tab_22)
player.tab.KD_field.setGeometry(QtCore.QRect(90, 124, 61, 20))
player.tab.KD_field.setObjectName("KD_field")
player.tab.xp_to_next_lvl_field = QtWidgets.QLineEdit(player.tab_22)
player.tab.xp_to_next_lvl_field.setGeometry(QtCore.QRect(170, 37, 61, 20))
player.tab.xp_to_next_lvl_field.setObjectName("xp_to_next_lvl_field")
player.tab.xp_labl = QtWidgets.QLabel(player.tab_22)
player.tab.xp_labl.setGeometry(QtCore.QRect(54, 37, 47, 13))
font = QtGui.QFont()
font.setPointSize(9)
player.tab.xp_labl.setFont(font)
player.tab.xp_labl.setObjectName("xp_labl")
player.tab.xp_prbar = QtWidgets.QProgressBar(player.tab_22)
player.tab.xp_prbar.setGeometry(QtCore.QRect(240, 37, 201, 23))
player.tab.xp_prbar.setStyleSheet("QProgressBar::chunk {\n"
"    text-align: center\n"
"}")
player.tab.xp_prbar.setProperty("value", 24)
player.tab.xp_prbar.setAlignment(QtCore.Qt.AlignCenter)
player.tab.xp_prbar.setObjectName("xp_prbar")
player.tab.xp_at_this_moment_field = QtWidgets.QLineEdit(player.tab_22)
player.tab.xp_at_this_moment_field.setGeometry(QtCore.QRect(90, 37, 61, 20))
player.tab.xp_at_this_moment_field.setObjectName("xp_at_this_moment_field")
player.tab.label_70 = QtWidgets.QLabel(player.tab_22)
player.tab.label_70.setGeometry(QtCore.QRect(160, 37, 16, 16))
player.tab.label_70.setObjectName("label_70")
player.tab.bon_mast_field = QtWidgets.QLineEdit(player.tab_22)
player.tab.bon_mast_field.setGeometry(QtCore.QRect(90, 66, 131, 20))
player.tab.bon_mast_field.setObjectName("bon_mast_field")
player.tab.bon_mast_labl = QtWidgets.QLabel(player.tab_22)
player.tab.bon_mast_labl.setGeometry(QtCore.QRect(33, 66, 61, 16))
font = QtGui.QFont()
font.setPointSize(9)
player.tab.bon_mast_labl.setFont(font)
player.tab.bon_mast_labl.setObjectName("bon_mast_labl")
player.tab.state_person.addTab(player.tab_22, "")
player.tab.add_mag_button = QtWidgets.QPushButton(player.tab)
player.tab.add_mag_button.setGeometry(QtCore.QRect(670, 725, 121, 31))
font = QtGui.QFont()
font.setPointSize(9)
player.tab.add_mag_button.setFont(font)
player.tab.add_mag_button.setObjectName("add_mag_button")
player.tab.red_view_mag_button = QtWidgets.QPushButton(player.tab)
player.tab.red_view_mag_button.setGeometry(QtCore.QRect(670, 759, 121, 41))
font = QtGui.QFont()
font.setPointSize(9)
player.tab.red_view_mag_button.setFont(font)
player.tab.red_view_mag_button.setObjectName("red_view_mag_button")
player.tab.delete_mag_button = QtWidgets.QPushButton(player.tab)
player.tab.delete_mag_button.setGeometry(QtCore.QRect(670, 804, 121, 31))
font = QtGui.QFont()
font.setPointSize(9)
player.tab.delete_mag_button.setFont(font)
player.tab.delete_mag_button.setObjectName("delete_mag_button")
player.tab.gridLayoutWidget_7 = QtWidgets.QWidget(player.tab)
player.tab.gridLayoutWidget_7.setGeometry(QtCore.QRect(670, 400, 121, 311))
player.tab.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
player.tab.gridLayout = QtWidgets.QGridLayout(player.tab.gridLayoutWidget_7)
player.tab.gridLayout.setContentsMargins(0, 0, 0, 0)
player.tab.gridLayout.setObjectName("gridLayout")
player.tab.mag_lvl9_can_use_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_7)
player.tab.mag_lvl9_can_use_field.setObjectName("mag_lvl9_can_use_field")
player.tab.gridLayout.addWidget(player.tab.mag_lvl9_can_use_field, 9, 3, 1, 1)
player.tab.label_14 = QtWidgets.QLabel(player.tab.gridLayoutWidget_7)
player.tab.label_14.setObjectName("label_14")
player.tab.gridLayout.addWidget(player.tab.label_14, 5, 2, 1, 1)
player.tab.label_9 = QtWidgets.QLabel(player.tab.gridLayoutWidget_7)
player.tab.label_9.setObjectName("label_9")
player.tab.gridLayout.addWidget(player.tab.label_9, 8, 0, 1, 1)
player.tab.label_5 = QtWidgets.QLabel(player.tab.gridLayoutWidget_7)
player.tab.label_5.setObjectName("label_5")
player.tab.gridLayout.addWidget(player.tab.label_5, 4, 0, 1, 1)
player.tab.label_10 = QtWidgets.QLabel(player.tab.gridLayoutWidget_7)
player.tab.label_10.setObjectName("label_10")
player.tab.gridLayout.addWidget(player.tab.label_10, 9, 0, 1, 1)
player.tab.label_6 = QtWidgets.QLabel(player.tab.gridLayoutWidget_7)
player.tab.label_6.setObjectName("label_6")
player.tab.gridLayout.addWidget(player.tab.label_6, 5, 0, 1, 1)
player.tab.label_16 = QtWidgets.QLabel(player.tab.gridLayoutWidget_7)
player.tab.label_16.setObjectName("label_16")
player.tab.gridLayout.addWidget(player.tab.label_16, 7, 2, 1, 1)
player.tab.label_12 = QtWidgets.QLabel(player.tab.gridLayoutWidget_7)
player.tab.label_12.setObjectName("label_12")
player.tab.gridLayout.addWidget(player.tab.label_12, 3, 2, 1, 1)
player.tab.label_7 = QtWidgets.QLabel(player.tab.gridLayoutWidget_7)
player.tab.label_7.setObjectName("label_7")
player.tab.gridLayout.addWidget(player.tab.label_7, 6, 0, 1, 1)
player.tab.label_2 = QtWidgets.QLabel(player.tab.gridLayoutWidget_7)
player.tab.label_2.setObjectName("label_2")
player.tab.gridLayout.addWidget(player.tab.label_2, 2, 0, 1, 1)
player.tab.label_3 = QtWidgets.QLabel(player.tab.gridLayoutWidget_7)
player.tab.label_3.setObjectName("label_3")
player.tab.gridLayout.addWidget(player.tab.label_3, 1, 2, 1, 1)
player.tab.mag_lvl9_used_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_7)
player.tab.mag_lvl9_used_field.setObjectName("mag_lvl9_used_field")
player.tab.gridLayout.addWidget(player.tab.mag_lvl9_used_field, 9, 1, 1, 1)
player.tab.label_17 = QtWidgets.QLabel(player.tab.gridLayoutWidget_7)
player.tab.label_17.setObjectName("label_17")
player.tab.gridLayout.addWidget(player.tab.label_17, 8, 2, 1, 1)
player.tab.label_4 = QtWidgets.QLabel(player.tab.gridLayoutWidget_7)
player.tab.label_4.setObjectName("label_4")
player.tab.gridLayout.addWidget(player.tab.label_4, 3, 0, 1, 1)
player.tab.label_13 = QtWidgets.QLabel(player.tab.gridLayoutWidget_7)
player.tab.label_13.setObjectName("label_13")
player.tab.gridLayout.addWidget(player.tab.label_13, 4, 2, 1, 1)
player.tab.label_11 = QtWidgets.QLabel(player.tab.gridLayoutWidget_7)
player.tab.label_11.setObjectName("label_11")
player.tab.gridLayout.addWidget(player.tab.label_11, 2, 2, 1, 1)
player.tab.label_15 = QtWidgets.QLabel(player.tab.gridLayoutWidget_7)
player.tab.label_15.setObjectName("label_15")
player.tab.gridLayout.addWidget(player.tab.label_15, 6, 2, 1, 1)
player.tab.label_8 = QtWidgets.QLabel(player.tab.gridLayoutWidget_7)
player.tab.label_8.setObjectName("label_8")
player.tab.gridLayout.addWidget(player.tab.label_8, 7, 0, 1, 1)
player.tab.label_18 = QtWidgets.QLabel(player.tab.gridLayoutWidget_7)
player.tab.label_18.setObjectName("label_18")
player.tab.gridLayout.addWidget(player.tab.label_18, 9, 2, 1, 1)
player.tab.label = QtWidgets.QLabel(player.tab.gridLayoutWidget_7)
player.tab.label.setObjectName("label")
player.tab.gridLayout.addWidget(player.tab.label, 1, 0, 1, 1)
player.tab.label_19 = QtWidgets.QLabel(player.tab.gridLayoutWidget_7)
player.tab.label_19.setObjectName("label_19")
player.tab.gridLayout.addWidget(player.tab.label_19, 0, 0, 1, 1)
player.tab.mag_lvl0_used_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_7)
player.tab.mag_lvl0_used_field.setObjectName("mag_lvl0_used_field")
player.tab.gridLayout.addWidget(player.tab.mag_lvl0_used_field, 0, 1, 1, 1)
player.tab.mag_lvl0_can_use_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_7)
player.tab.mag_lvl0_can_use_field.setObjectName("mag_lvl0_can_use_field")
player.tab.gridLayout.addWidget(player.tab.mag_lvl0_can_use_field, 0, 3, 1, 1)
player.tab.mag_lvl1_can_use_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_7)
player.tab.mag_lvl1_can_use_field.setObjectName("mag_lvl1_can_use_field")
player.tab.gridLayout.addWidget(player.tab.mag_lvl1_can_use_field, 1, 3, 1, 1)
player.tab.mag_lvl1_used_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_7)
player.tab.mag_lvl1_used_field.setObjectName("mag_lvl1_used_field")
player.tab.gridLayout.addWidget(player.tab.mag_lvl1_used_field, 1, 1, 1, 1)
player.tab.mag_lvl2_used_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_7)
player.tab.mag_lvl2_used_field.setObjectName("mag_lvl2_used_field")
player.tab.gridLayout.addWidget(player.tab.mag_lvl2_used_field, 2, 1, 1, 1)
player.tab.mag_lvl2_can_use_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_7)
player.tab.mag_lvl2_can_use_field.setObjectName("mag_lvl2_can_use_field")
player.tab.gridLayout.addWidget(player.tab.mag_lvl2_can_use_field, 2, 3, 1, 1)
player.tab.mag_lvl3_used_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_7)
player.tab.mag_lvl3_used_field.setObjectName("mag_lvl3_used_field")
player.tab.gridLayout.addWidget(player.tab.mag_lvl3_used_field, 3, 1, 1, 1)
player.tab.mag_lvl3_can_use_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_7)
player.tab.mag_lvl3_can_use_field.setObjectName("mag_lvl3_can_use_field")
player.tab.gridLayout.addWidget(player.tab.mag_lvl3_can_use_field, 3, 3, 1, 1)
player.tab.mag_lvl4_used_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_7)
player.tab.mag_lvl4_used_field.setObjectName("mag_lvl4_used_field")
player.tab.gridLayout.addWidget(player.tab.mag_lvl4_used_field, 4, 1, 1, 1)
player.tab.mag_lvl4_can_use_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_7)
player.tab.mag_lvl4_can_use_field.setObjectName("mag_lvl4_can_use_field")
player.tab.gridLayout.addWidget(player.tab.mag_lvl4_can_use_field, 4, 3, 1, 1)
player.tab.mag_lvl5_used_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_7)
player.tab.mag_lvl5_used_field.setObjectName("mag_lvl5_used_field")
player.tab.gridLayout.addWidget(player.tab.mag_lvl5_used_field, 5, 1, 1, 1)
player.tab.mag_lvl5_can_use_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_7)
player.tab.mag_lvl5_can_use_field.setObjectName("mag_lvl5_can_use_field")
player.tab.gridLayout.addWidget(player.tab.mag_lvl5_can_use_field, 5, 3, 1, 1)
player.tab.mag_lvl6_used_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_7)
player.tab.mag_lvl6_used_field.setObjectName("mag_lvl6_used_field")
player.tab.gridLayout.addWidget(player.tab.mag_lvl6_used_field, 6, 1, 1, 1)
player.tab.mag_lvl6_can_use_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_7)
player.tab.mag_lvl6_can_use_field.setObjectName("mag_lvl6_can_use_field")
player.tab.gridLayout.addWidget(player.tab.mag_lvl6_can_use_field, 6, 3, 1, 1)
player.tab.mag_lvl7_used_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_7)
player.tab.mag_lvl7_used_field.setObjectName("mag_lvl7_used_field")
player.tab.gridLayout.addWidget(player.tab.mag_lvl7_used_field, 7, 1, 1, 1)
player.tab.mag_lvl7_can_use_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_7)
player.tab.mag_lvl7_can_use_field.setObjectName("mag_lvl7_can_use_field")
player.tab.gridLayout.addWidget(player.tab.mag_lvl7_can_use_field, 7, 3, 1, 1)
player.tab.mag_lvl8_used_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_7)
player.tab.mag_lvl8_used_field.setObjectName("mag_lvl8_used_field")
player.tab.gridLayout.addWidget(player.tab.mag_lvl8_used_field, 8, 1, 1, 1)
player.tab.mag_lvl8_can_use_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_7)
player.tab.mag_lvl8_can_use_field.setObjectName("mag_lvl8_can_use_field")
player.tab.gridLayout.addWidget(player.tab.mag_lvl8_can_use_field, 8, 3, 1, 1)
player.tab.Usefull_buttons = QtWidgets.QGroupBox(player.tab)
player.tab.Usefull_buttons.setEnabled(False)
player.tab.Usefull_buttons.setGeometry(QtCore.QRect(790, 63, 301, 331))
player.tab.Usefull_buttons.setToolTipDuration(-1)
player.tab.Usefull_buttons.setLayoutDirection(QtCore.Qt.LeftToRight)
player.tab.Usefull_buttons.setObjectName("Usefull_buttons")
player.tab.calculator_button = QtWidgets.QPushButton(player.tab.Usefull_buttons)
player.tab.calculator_button.setGeometry(QtCore.QRect(7, 22, 75, 23))
player.tab.calculator_button.setObjectName("calculator_button")
player.tab.time_button = QtWidgets.QPushButton(player.tab.Usefull_buttons)
player.tab.time_button.setGeometry(QtCore.QRect(8, 50, 75, 23))
player.tab.time_button.setFocusPolicy(QtCore.Qt.ClickFocus)
player.tab.time_button.setObjectName("time_button")
player.tab.add_mag_lvl0_2 = QtWidgets.QPushButton(player.tab)
player.tab.add_mag_lvl0_2.setGeometry(QtCore.QRect(840, 830, 75, 23))
font = QtGui.QFont()
font.setPointSize(9)
player.tab.add_mag_lvl0_2.setFont(font)
player.tab.add_mag_lvl0_2.setObjectName("add_mag_lvl0_2")
player.tab.pushButton_4 = QtWidgets.QPushButton(player.tab)
player.tab.pushButton_4.setGeometry(QtCore.QRect(920, 830, 75, 23))
font = QtGui.QFont()
font.setPointSize(9)
player.tab.pushButton_4.setFont(font)
player.tab.pushButton_4.setObjectName("pushButton_4")
player.tab.pushButton_5 = QtWidgets.QPushButton(player.tab)
player.tab.pushButton_5.setGeometry(QtCore.QRect(1000, 830, 75, 23))
font = QtGui.QFont()
font.setPointSize(9)
player.tab.pushButton_5.setFont(font)
player.tab.pushButton_5.setObjectName("pushButton_5")
player.tab.characters_tab.addTab(player.tab, "")
player.tab = QtWidgets.QWidget()
player.tab.setObjectName("tab")
player.tab.characters_tab.addTab(player.tab, "")
MainWindow.setCentralWidget(player.tab.centralwidget)
player.tab.menuBar = QtWidgets.QMenuBar(MainWindow)
player.tab.menuBar.setGeometry(QtCore.QRect(0, 0, 1100, 21))
font = QtGui.QFont()
font.setFamily("Source Code Pro Semibold")
font.setStrikeOut(False)
player.tab.menuBar.setFont(font)
player.tab.menuBar.setLayoutDirection(QtCore.Qt.LeftToRight)
player.tab.menuBar.setAutoFillBackground(True)
player.tab.menuBar.setDefaultUp(False)
player.tab.menuBar.setObjectName("menuBar")
player.tab.character_menu = QtWidgets.QMenu(player.tab.menuBar)
player.tab.character_menu.setObjectName("character_menu")
player.tab.book_menu = QtWidgets.QMenu(player.tab.menuBar)
player.tab.book_menu.setObjectName("book_menu")
player.tab.instruments_menu = QtWidgets.QMenu(player.tab.menuBar)
player.tab.instruments_menu.setObjectName("instruments_menu")
player.tab.instr_character = QtWidgets.QMenu(player.tab.instruments_menu)
player.tab.instr_character.setObjectName("instr_character")
player.tab.name_generator = QtWidgets.QMenu(player.tab.instr_character)
player.tab.name_generator.setObjectName("name_generator")
player.tab.bandit_name_generator = QtWidgets.QMenu(player.tab.instr_character)
player.tab.bandit_name_generator.setObjectName("bandit_name_generator")
player.tab.harakter_generator = QtWidgets.QMenu(player.tab.instr_character)
player.tab.harakter_generator.setObjectName("harakter_generator")
player.tab.country_name_generator = QtWidgets.QMenu(player.tab.instr_character)
player.tab.country_name_generator.setObjectName("country_name_generator")
player.tab.make_location = QtWidgets.QMenu(player.tab.instruments_menu)
player.tab.make_location.setObjectName("make_location")
player.tab.home_generator = QtWidgets.QMenu(player.tab.make_location)
player.tab.home_generator.setObjectName("home_generator")
player.tab.city_generator = QtWidgets.QMenu(player.tab.make_location)
player.tab.city_generator.setObjectName("city_generator")
player.tab.usefull_menu = QtWidgets.QMenu(player.tab.menuBar)
player.tab.usefull_menu.setObjectName("usefull_menu")
player.tab.bestiary = QtWidgets.QMenu(player.tab.usefull_menu)
player.tab.bestiary.setObjectName("bestiary")
player.tab.items = QtWidgets.QMenu(player.tab.usefull_menu)
player.tab.items.setObjectName("items")
player.tab.magic_items = QtWidgets.QMenu(player.tab.items)
player.tab.magic_items.setObjectName("magic_items")
player.tab.normal_items = QtWidgets.QMenu(player.tab.items)
player.tab.normal_items.setObjectName("normal_items")
player.tab.magic = QtWidgets.QMenu(player.tab.usefull_menu)
player.tab.magic.setObjectName("magic")
player.tab.cubes = QtWidgets.QMenu(player.tab.menuBar)
player.tab.cubes.setObjectName("cubes")
player.tab.configs = QtWidgets.QMenu(player.tab.menuBar)
player.tab.configs.setObjectName("configs")
player.tab.vk_group = QtWidgets.QMenu(player.tab.menuBar)
player.tab.vk_group.setObjectName("vk_group")
player.tab.help = QtWidgets.QMenu(player.tab.menuBar)
player.tab.help.setTearOffEnabled(False)
player.tab.help.setObjectName("help")
MainWindow.setMenuBar(player.tab.menuBar)
player.tab.add_character = QtWidgets.QAction(MainWindow)
player.tab.add_character.setObjectName("add_character")
player.tab.load_character = QtWidgets.QAction(MainWindow)
