player.tab.caractersistics = QtWidgets.QTabWidget(player.tab)
player.tab.caractersistics.setGeometry(QtCore.QRect(0, 400, 341, 461))
font = QtGui.QFont()
font.setFamily("MS Shell Dlg 2")
font.setPointSize(8)
player.tab.caractersistics.setFont(font)
player.tab.caractersistics.setTabPosition(QtWidgets.QTabWidget.West)
player.tab.caractersistics.setObjectName("caractersistics")
player.tab.characteristics_strong = QtWidgets.QWidget()
player.tab.characteristics_strong.setObjectName("characteristics_strong")
player.tab.gridLayoutWidget = QtWidgets.QWidget(player.tab.characteristics_strong)
player.tab.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 311, 131))
player.tab.gridLayoutWidget.setObjectName("gridLayoutWidget")
player.tab.cells_strong = QtWidgets.QGridLayout(player.tab.gridLayoutWidget)
player.tab.cells_strong.setContentsMargins(10, 0, 0, 0)
player.tab.cells_strong.setObjectName("cells_strong")
player.tab.line_28 = QtWidgets.QFrame(player.tab.gridLayoutWidget)
player.tab.line_28.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_28.setObjectName("line_28")
player.tab.cells_strong.addWidget(player.tab.line_28, 3, 5, 1, 1)
player.tab.line_26 = QtWidgets.QFrame(player.tab.gridLayoutWidget)
player.tab.line_26.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_26.setObjectName("line_26")
player.tab.cells_strong.addWidget(player.tab.line_26, 1, 5, 1, 1)
player.tab.line_2 = QtWidgets.QFrame(player.tab.gridLayoutWidget)
player.tab.line_2.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_2.setObjectName("line_2")
player.tab.cells_strong.addWidget(player.tab.line_2, 3, 2, 1, 1)
player.tab.athletics_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget)
player.tab.athletics_field.setObjectName("athletics_field")
player.tab.cells_strong.addWidget(player.tab.athletics_field, 2, 6, 1, 1)
player.tab.line_24 = QtWidgets.QFrame(player.tab.gridLayoutWidget)
player.tab.line_24.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_24.setObjectName("line_24")
player.tab.cells_strong.addWidget(player.tab.line_24, 5, 3, 1, 1)
player.tab.line_18 = QtWidgets.QFrame(player.tab.gridLayoutWidget)
player.tab.line_18.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_18.setObjectName("line_18")
player.tab.cells_strong.addWidget(player.tab.line_18, 1, 1, 1, 1)
player.tab.athletics_labl = QtWidgets.QLabel(player.tab.gridLayoutWidget)
player.tab.athletics_labl.setObjectName("athletics_labl")
player.tab.cells_strong.addWidget(player.tab.athletics_labl, 2, 0, 1, 1)
player.tab.line_16 = QtWidgets.QFrame(player.tab.gridLayoutWidget)
player.tab.line_16.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_16.setObjectName("line_16")
player.tab.cells_strong.addWidget(player.tab.line_16, 5, 1, 1, 1)
player.tab.line = QtWidgets.QFrame(player.tab.gridLayoutWidget)
player.tab.line.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line.setObjectName("line")
player.tab.cells_strong.addWidget(player.tab.line, 1, 2, 1, 1)
player.tab.line_19 = QtWidgets.QFrame(player.tab.gridLayoutWidget)
player.tab.line_19.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_19.setObjectName("line_19")
player.tab.cells_strong.addWidget(player.tab.line_19, 0, 3, 1, 1)
player.tab.line_4 = QtWidgets.QFrame(player.tab.gridLayoutWidget)
player.tab.line_4.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_4.setObjectName("line_4")
player.tab.cells_strong.addWidget(player.tab.line_4, 1, 0, 1, 1)
player.tab.mod_strong_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget)
player.tab.mod_strong_field.setObjectName("mod_strong_field")
player.tab.cells_strong.addWidget(player.tab.mod_strong_field, 0, 6, 1, 1)
player.tab.line_9 = QtWidgets.QFrame(player.tab.gridLayoutWidget)
player.tab.line_9.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_9.setObjectName("line_9")
player.tab.cells_strong.addWidget(player.tab.line_9, 3, 6, 1, 1)
player.tab.save_giving_labl = QtWidgets.QLabel(player.tab.gridLayoutWidget)
player.tab.save_giving_labl.setObjectName("save_giving_labl")
player.tab.cells_strong.addWidget(player.tab.save_giving_labl, 4, 0, 1, 1)
player.tab.line_30 = QtWidgets.QFrame(player.tab.gridLayoutWidget)
player.tab.line_30.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_30.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_30.setObjectName("line_30")
player.tab.cells_strong.addWidget(player.tab.line_30, 5, 5, 1, 1)
player.tab.line_12 = QtWidgets.QFrame(player.tab.gridLayoutWidget)
player.tab.line_12.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_12.setObjectName("line_12")
player.tab.cells_strong.addWidget(player.tab.line_12, 5, 6, 1, 1)
player.tab.strong_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget)
player.tab.strong_field.setObjectName("strong_field")
player.tab.cells_strong.addWidget(player.tab.strong_field, 0, 2, 1, 1)
player.tab.line_5 = QtWidgets.QFrame(player.tab.gridLayoutWidget)
player.tab.line_5.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_5.setObjectName("line_5")
player.tab.cells_strong.addWidget(player.tab.line_5, 1, 4, 1, 1)
player.tab.line_13 = QtWidgets.QFrame(player.tab.gridLayoutWidget)
player.tab.line_13.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_13.setObjectName("line_13")
player.tab.cells_strong.addWidget(player.tab.line_13, 0, 1, 1, 1)
player.tab.line_21 = QtWidgets.QFrame(player.tab.gridLayoutWidget)
player.tab.line_21.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_21.setObjectName("line_21")
player.tab.cells_strong.addWidget(player.tab.line_21, 2, 3, 1, 1)
player.tab.line_29 = QtWidgets.QFrame(player.tab.gridLayoutWidget)
player.tab.line_29.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_29.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_29.setObjectName("line_29")
player.tab.cells_strong.addWidget(player.tab.line_29, 4, 5, 1, 1)
player.tab.line_27 = QtWidgets.QFrame(player.tab.gridLayoutWidget)
player.tab.line_27.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_27.setObjectName("line_27")
player.tab.cells_strong.addWidget(player.tab.line_27, 2, 5, 1, 1)
player.tab.line_6 = QtWidgets.QFrame(player.tab.gridLayoutWidget)
player.tab.line_6.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_6.setObjectName("line_6")
player.tab.cells_strong.addWidget(player.tab.line_6, 1, 6, 1, 1)
player.tab.line_8 = QtWidgets.QFrame(player.tab.gridLayoutWidget)
player.tab.line_8.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_8.setObjectName("line_8")
player.tab.cells_strong.addWidget(player.tab.line_8, 3, 4, 1, 1)
player.tab.line_23 = QtWidgets.QFrame(player.tab.gridLayoutWidget)
player.tab.line_23.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_23.setObjectName("line_23")
player.tab.cells_strong.addWidget(player.tab.line_23, 4, 3, 1, 1)
player.tab.mod_strong_labl = QtWidgets.QLabel(player.tab.gridLayoutWidget)
player.tab.mod_strong_labl.setObjectName("mod_strong_labl")
player.tab.cells_strong.addWidget(player.tab.mod_strong_labl, 0, 4, 1, 1)
player.tab.line_3 = QtWidgets.QFrame(player.tab.gridLayoutWidget)
player.tab.line_3.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_3.setObjectName("line_3")
player.tab.cells_strong.addWidget(player.tab.line_3, 5, 2, 1, 1)
player.tab.line_22 = QtWidgets.QFrame(player.tab.gridLayoutWidget)
player.tab.line_22.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_22.setObjectName("line_22")
player.tab.cells_strong.addWidget(player.tab.line_22, 3, 3, 1, 1)
player.tab.athletics_checkboxhaving = QtWidgets.QCheckBox(player.tab.gridLayoutWidget)
player.tab.athletics_checkboxhaving.setObjectName("athletics_checkboxhaving")
player.tab.cells_strong.addWidget(player.tab.athletics_checkboxhaving, 2, 4, 1, 1)
player.tab.line_11 = QtWidgets.QFrame(player.tab.gridLayoutWidget)
player.tab.line_11.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_11.setObjectName("line_11")
player.tab.cells_strong.addWidget(player.tab.line_11, 5, 4, 1, 1)
player.tab.line_7 = QtWidgets.QFrame(player.tab.gridLayoutWidget)
player.tab.line_7.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_7.setObjectName("line_7")
player.tab.cells_strong.addWidget(player.tab.line_7, 3, 0, 1, 1)
player.tab.line_10 = QtWidgets.QFrame(player.tab.gridLayoutWidget)
player.tab.line_10.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_10.setObjectName("line_10")
player.tab.cells_strong.addWidget(player.tab.line_10, 5, 0, 1, 1)
player.tab.line_17 = QtWidgets.QFrame(player.tab.gridLayoutWidget)
player.tab.line_17.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_17.setObjectName("line_17")
player.tab.cells_strong.addWidget(player.tab.line_17, 3, 1, 1, 1)
player.tab.line_20 = QtWidgets.QFrame(player.tab.gridLayoutWidget)
player.tab.line_20.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_20.setObjectName("line_20")
player.tab.cells_strong.addWidget(player.tab.line_20, 1, 3, 1, 1)
player.tab.znachenie_strong_labl = QtWidgets.QLabel(player.tab.gridLayoutWidget)
player.tab.znachenie_strong_labl.setObjectName("znachenie_strong_labl")
player.tab.cells_strong.addWidget(player.tab.znachenie_strong_labl, 0, 0, 1, 1)
player.tab.line_25 = QtWidgets.QFrame(player.tab.gridLayoutWidget)
player.tab.line_25.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_25.setObjectName("line_25")
player.tab.cells_strong.addWidget(player.tab.line_25, 0, 5, 1, 1)
player.tab.line_15 = QtWidgets.QFrame(player.tab.gridLayoutWidget)
player.tab.line_15.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_15.setObjectName("line_15")
player.tab.cells_strong.addWidget(player.tab.line_15, 4, 1, 1, 1)
player.tab.line_14 = QtWidgets.QFrame(player.tab.gridLayoutWidget)
player.tab.line_14.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_14.setObjectName("line_14")
player.tab.cells_strong.addWidget(player.tab.line_14, 2, 1, 1, 1)
player.tab.competention_athletics_checkbox = QtWidgets.QCheckBox(player.tab.gridLayoutWidget)
player.tab.competention_athletics_checkbox.setObjectName("competention_athletics_checkbox")
player.tab.cells_strong.addWidget(player.tab.competention_athletics_checkbox, 2, 2, 1, 1)
player.tab.save_giving_strong_checkboxhaving = QtWidgets.QCheckBox(player.tab.gridLayoutWidget)
player.tab.save_giving_strong_checkboxhaving.setObjectName("save_giving_strong_checkboxhaving")
player.tab.cells_strong.addWidget(player.tab.save_giving_strong_checkboxhaving, 4, 4, 1, 1)
player.tab.description_strong_labl = QtWidgets.QLabel(player.tab.characteristics_strong)
player.tab.description_strong_labl.setGeometry(QtCore.QRect(10, 140, 281, 271))
player.tab.description_strong_labl.setTextFormat(QtCore.Qt.AutoText)
player.tab.description_strong_labl.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
player.tab.description_strong_labl.setWordWrap(False)
player.tab.description_strong_labl.setOpenExternalLinks(False)
player.tab.description_strong_labl.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
player.tab.description_strong_labl.setObjectName("description_strong_labl")
player.tab.caractersistics.addTab(player.tab.characteristics_strong, "")
player.tab.characteristics_dexterity = QtWidgets.QWidget()
player.tab.characteristics_dexterity.setObjectName("characteristics_dexterity")
player.tab.gridLayoutWidget_2 = QtWidgets.QWidget(player.tab.characteristics_dexterity)
player.tab.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 311, 181))
player.tab.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
player.tab.cell_desterity = QtWidgets.QGridLayout(player.tab.gridLayoutWidget_2)
player.tab.cell_desterity.setContentsMargins(10, 0, 0, 0)
player.tab.cell_desterity.setObjectName("cell_desterity")
player.tab.line_39 = QtWidgets.QFrame(player.tab.gridLayoutWidget_2)
player.tab.line_39.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_39.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_39.setObjectName("line_39")
player.tab.cell_desterity.addWidget(player.tab.line_39, 9, 4, 1, 1)
player.tab.line_63 = QtWidgets.QFrame(player.tab.gridLayoutWidget_2)
player.tab.line_63.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_63.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_63.setObjectName("line_63")
player.tab.cell_desterity.addWidget(player.tab.line_63, 5, 2, 1, 1)
player.tab.line_51 = QtWidgets.QFrame(player.tab.gridLayoutWidget_2)
player.tab.line_51.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_51.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_51.setObjectName("line_51")
player.tab.cell_desterity.addWidget(player.tab.line_51, 1, 0, 1, 1)
player.tab.line_57 = QtWidgets.QFrame(player.tab.gridLayoutWidget_2)
player.tab.line_57.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_57.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_57.setObjectName("line_57")
player.tab.cell_desterity.addWidget(player.tab.line_57, 8, 5, 1, 1)
player.tab.save_giving_labl_2 = QtWidgets.QLabel(player.tab.gridLayoutWidget_2)
player.tab.save_giving_labl_2.setObjectName("save_giving_labl_2")
player.tab.cell_desterity.addWidget(player.tab.save_giving_labl_2, 8, 0, 1, 1)
player.tab.line_32 = QtWidgets.QFrame(player.tab.gridLayoutWidget_2)
player.tab.line_32.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_32.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_32.setObjectName("line_32")
player.tab.cell_desterity.addWidget(player.tab.line_32, 9, 1, 1, 1)
player.tab.line_66 = QtWidgets.QFrame(player.tab.gridLayoutWidget_2)
player.tab.line_66.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_66.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_66.setObjectName("line_66")
player.tab.cell_desterity.addWidget(player.tab.line_66, 7, 2, 1, 1)
player.tab.line_68 = QtWidgets.QFrame(player.tab.gridLayoutWidget_2)
player.tab.line_68.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_68.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_68.setObjectName("line_68")
player.tab.cell_desterity.addWidget(player.tab.line_68, 7, 6, 1, 1)
player.tab.acrobatica_checkboxhaving = QtWidgets.QCheckBox(player.tab.gridLayoutWidget_2)
player.tab.acrobatica_checkboxhaving.setObjectName("acrobatica_checkboxhaving")
player.tab.cell_desterity.addWidget(player.tab.acrobatica_checkboxhaving, 2, 4, 1, 1)
player.tab.line_65 = QtWidgets.QFrame(player.tab.gridLayoutWidget_2)
player.tab.line_65.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_65.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_65.setObjectName("line_65")
player.tab.cell_desterity.addWidget(player.tab.line_65, 5, 6, 1, 1)
player.tab.line_54 = QtWidgets.QFrame(player.tab.gridLayoutWidget_2)
player.tab.line_54.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_54.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_54.setObjectName("line_54")
player.tab.cell_desterity.addWidget(player.tab.line_54, 1, 5, 1, 1)
player.tab.lovk_ryk_labl = QtWidgets.QLabel(player.tab.gridLayoutWidget_2)
player.tab.lovk_ryk_labl.setObjectName("lovk_ryk_labl")
player.tab.cell_desterity.addWidget(player.tab.lovk_ryk_labl, 4, 0, 1, 1)
player.tab.line_52 = QtWidgets.QFrame(player.tab.gridLayoutWidget_2)
player.tab.line_52.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_52.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_52.setObjectName("line_52")
player.tab.cell_desterity.addWidget(player.tab.line_52, 1, 2, 1, 1)
player.tab.line_40 = QtWidgets.QFrame(player.tab.gridLayoutWidget_2)
player.tab.line_40.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_40.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_40.setObjectName("line_40")
player.tab.cell_desterity.addWidget(player.tab.line_40, 3, 6, 1, 1)
player.tab.line_45 = QtWidgets.QFrame(player.tab.gridLayoutWidget_2)
player.tab.line_45.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_45.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_45.setObjectName("line_45")
player.tab.cell_desterity.addWidget(player.tab.line_45, 8, 1, 1, 1)
player.tab.line_37 = QtWidgets.QFrame(player.tab.gridLayoutWidget_2)
player.tab.line_37.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_37.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_37.setObjectName("line_37")
player.tab.cell_desterity.addWidget(player.tab.line_37, 2, 1, 1, 1)
player.tab.line_36 = QtWidgets.QFrame(player.tab.gridLayoutWidget_2)
player.tab.line_36.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_36.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_36.setObjectName("line_36")
player.tab.cell_desterity.addWidget(player.tab.line_36, 9, 0, 1, 1)
player.tab.line_48 = QtWidgets.QFrame(player.tab.gridLayoutWidget_2)
player.tab.line_48.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_48.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_48.setObjectName("line_48")
player.tab.cell_desterity.addWidget(player.tab.line_48, 9, 6, 1, 1)
player.tab.line_47 = QtWidgets.QFrame(player.tab.gridLayoutWidget_2)
player.tab.line_47.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_47.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_47.setObjectName("line_47")
player.tab.cell_desterity.addWidget(player.tab.line_47, 3, 1, 1, 1)
player.tab.line_55 = QtWidgets.QFrame(player.tab.gridLayoutWidget_2)
player.tab.line_55.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_55.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_55.setObjectName("line_55")
player.tab.cell_desterity.addWidget(player.tab.line_55, 2, 5, 1, 1)
player.tab.line_49 = QtWidgets.QFrame(player.tab.gridLayoutWidget_2)
player.tab.line_49.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_49.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_49.setObjectName("line_49")
player.tab.cell_desterity.addWidget(player.tab.line_49, 0, 3, 1, 1)
player.tab.dexterity_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_2)
player.tab.dexterity_field.setObjectName("dexterity_field")
player.tab.cell_desterity.addWidget(player.tab.dexterity_field, 0, 2, 1, 1)
player.tab.line_61 = QtWidgets.QFrame(player.tab.gridLayoutWidget_2)
player.tab.line_61.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_61.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_61.setObjectName("line_61")
player.tab.cell_desterity.addWidget(player.tab.line_61, 7, 0, 1, 1)
player.tab.save_giving_dexterity_checkboxhaving = QtWidgets.QCheckBox(player.tab.gridLayoutWidget_2)
player.tab.save_giving_dexterity_checkboxhaving.setObjectName("save_giving_dexterity_checkboxhaving")
player.tab.cell_desterity.addWidget(player.tab.save_giving_dexterity_checkboxhaving, 8, 4, 1, 1)
player.tab.line_50 = QtWidgets.QFrame(player.tab.gridLayoutWidget_2)
player.tab.line_50.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_50.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_50.setObjectName("line_50")
player.tab.cell_desterity.addWidget(player.tab.line_50, 8, 3, 1, 1)
player.tab.line_46 = QtWidgets.QFrame(player.tab.gridLayoutWidget_2)
player.tab.line_46.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_46.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_46.setObjectName("line_46")
player.tab.cell_desterity.addWidget(player.tab.line_46, 3, 2, 1, 1)
player.tab.mod_strong_labl_2 = QtWidgets.QLabel(player.tab.gridLayoutWidget_2)
player.tab.mod_strong_labl_2.setObjectName("mod_strong_labl_2")
player.tab.cell_desterity.addWidget(player.tab.mod_strong_labl_2, 0, 4, 1, 1)
player.tab.acrobatica_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_2)
player.tab.acrobatica_field.setObjectName("acrobatica_field")
player.tab.cell_desterity.addWidget(player.tab.acrobatica_field, 2, 6, 1, 1)
player.tab.line_60 = QtWidgets.QFrame(player.tab.gridLayoutWidget_2)
player.tab.line_60.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_60.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_60.setObjectName("line_60")
player.tab.cell_desterity.addWidget(player.tab.line_60, 1, 6, 1, 1)
player.tab.stealth_labl = QtWidgets.QLabel(player.tab.gridLayoutWidget_2)
player.tab.stealth_labl.setObjectName("stealth_labl")
player.tab.cell_desterity.addWidget(player.tab.stealth_labl, 6, 0, 1, 1)
player.tab.line_42 = QtWidgets.QFrame(player.tab.gridLayoutWidget_2)
player.tab.line_42.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_42.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_42.setObjectName("line_42")
player.tab.cell_desterity.addWidget(player.tab.line_42, 3, 3, 1, 1)
player.tab.line_53 = QtWidgets.QFrame(player.tab.gridLayoutWidget_2)
player.tab.line_53.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_53.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_53.setObjectName("line_53")
player.tab.cell_desterity.addWidget(player.tab.line_53, 0, 5, 1, 1)
player.tab.line_62 = QtWidgets.QFrame(player.tab.gridLayoutWidget_2)
player.tab.line_62.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_62.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_62.setObjectName("line_62")
player.tab.cell_desterity.addWidget(player.tab.line_62, 5, 0, 1, 1)
player.tab.line_64 = QtWidgets.QFrame(player.tab.gridLayoutWidget_2)
player.tab.line_64.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_64.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_64.setObjectName("line_64")
player.tab.cell_desterity.addWidget(player.tab.line_64, 5, 4, 1, 1)
player.tab.acrobatica_labl = QtWidgets.QLabel(player.tab.gridLayoutWidget_2)
player.tab.acrobatica_labl.setObjectName("acrobatica_labl")
player.tab.cell_desterity.addWidget(player.tab.acrobatica_labl, 2, 0, 1, 1)
player.tab.acrobatica_checkbox = QtWidgets.QCheckBox(player.tab.gridLayoutWidget_2)
player.tab.acrobatica_checkbox.setObjectName("acrobatica_checkbox")
player.tab.cell_desterity.addWidget(player.tab.acrobatica_checkbox, 2, 2, 1, 1)
player.tab.line_33 = QtWidgets.QFrame(player.tab.gridLayoutWidget_2)
player.tab.line_33.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_33.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_33.setObjectName("line_33")
player.tab.cell_desterity.addWidget(player.tab.line_33, 9, 2, 1, 1)
player.tab.line_38 = QtWidgets.QFrame(player.tab.gridLayoutWidget_2)
player.tab.line_38.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_38.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_38.setObjectName("line_38")
player.tab.cell_desterity.addWidget(player.tab.line_38, 1, 3, 1, 1)
player.tab.line_34 = QtWidgets.QFrame(player.tab.gridLayoutWidget_2)
player.tab.line_34.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_34.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_34.setObjectName("line_34")
player.tab.cell_desterity.addWidget(player.tab.line_34, 3, 0, 1, 1)
player.tab.line_67 = QtWidgets.QFrame(player.tab.gridLayoutWidget_2)
player.tab.line_67.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_67.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_67.setObjectName("line_67")
player.tab.cell_desterity.addWidget(player.tab.line_67, 7, 4, 1, 1)
player.tab.znachenie_dexterity_labl = QtWidgets.QLabel(player.tab.gridLayoutWidget_2)
player.tab.znachenie_dexterity_labl.setObjectName("znachenie_dexterity_labl")
player.tab.cell_desterity.addWidget(player.tab.znachenie_dexterity_labl, 0, 0, 1, 1)
player.tab.line_44 = QtWidgets.QFrame(player.tab.gridLayoutWidget_2)
player.tab.line_44.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_44.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_44.setObjectName("line_44")
player.tab.cell_desterity.addWidget(player.tab.line_44, 0, 1, 1, 1)
player.tab.line_43 = QtWidgets.QFrame(player.tab.gridLayoutWidget_2)
player.tab.line_43.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_43.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_43.setObjectName("line_43")
player.tab.cell_desterity.addWidget(player.tab.line_43, 2, 3, 1, 1)
player.tab.line_31 = QtWidgets.QFrame(player.tab.gridLayoutWidget_2)
player.tab.line_31.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_31.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_31.setObjectName("line_31")
player.tab.cell_desterity.addWidget(player.tab.line_31, 3, 4, 1, 1)
player.tab.line_59 = QtWidgets.QFrame(player.tab.gridLayoutWidget_2)
player.tab.line_59.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_59.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_59.setObjectName("line_59")
player.tab.cell_desterity.addWidget(player.tab.line_59, 1, 4, 1, 1)
player.tab.mod_dexterity_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_2)
player.tab.mod_dexterity_field.setObjectName("mod_dexterity_field")
player.tab.cell_desterity.addWidget(player.tab.mod_dexterity_field, 0, 6, 1, 1)
player.tab.line_35 = QtWidgets.QFrame(player.tab.gridLayoutWidget_2)
player.tab.line_35.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_35.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_35.setObjectName("line_35")
player.tab.cell_desterity.addWidget(player.tab.line_35, 9, 3, 1, 1)
player.tab.line_58 = QtWidgets.QFrame(player.tab.gridLayoutWidget_2)
player.tab.line_58.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_58.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_58.setObjectName("line_58")
player.tab.cell_desterity.addWidget(player.tab.line_58, 9, 5, 1, 1)
player.tab.line_56 = QtWidgets.QFrame(player.tab.gridLayoutWidget_2)
player.tab.line_56.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_56.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_56.setObjectName("line_56")
player.tab.cell_desterity.addWidget(player.tab.line_56, 3, 5, 1, 1)
player.tab.line_41 = QtWidgets.QFrame(player.tab.gridLayoutWidget_2)
player.tab.line_41.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_41.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_41.setObjectName("line_41")
player.tab.cell_desterity.addWidget(player.tab.line_41, 1, 1, 1, 1)
player.tab.lovk_ryk_checkbox = QtWidgets.QCheckBox(player.tab.gridLayoutWidget_2)
player.tab.lovk_ryk_checkbox.setObjectName("lovk_ryk_checkbox")
player.tab.cell_desterity.addWidget(player.tab.lovk_ryk_checkbox, 4, 2, 1, 1)
player.tab.stealth_checkbox = QtWidgets.QCheckBox(player.tab.gridLayoutWidget_2)
player.tab.stealth_checkbox.setObjectName("stealth_checkbox")
player.tab.cell_desterity.addWidget(player.tab.stealth_checkbox, 6, 2, 1, 1)
player.tab.lovk_ryk_checkboxhaving = QtWidgets.QCheckBox(player.tab.gridLayoutWidget_2)
player.tab.lovk_ryk_checkboxhaving.setObjectName("lovk_ryk_checkboxhaving")
player.tab.cell_desterity.addWidget(player.tab.lovk_ryk_checkboxhaving, 4, 4, 1, 1)
player.tab.stealth_checkboxhaving = QtWidgets.QCheckBox(player.tab.gridLayoutWidget_2)
player.tab.stealth_checkboxhaving.setObjectName("stealth_checkboxhaving")
player.tab.cell_desterity.addWidget(player.tab.stealth_checkboxhaving, 6, 4, 1, 1)
player.tab.lovk_ryk_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_2)
player.tab.lovk_ryk_field.setObjectName("lovk_ryk_field")
player.tab.cell_desterity.addWidget(player.tab.lovk_ryk_field, 4, 6, 1, 1)
player.tab.stealth_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_2)
player.tab.stealth_field.setObjectName("stealth_field")
player.tab.cell_desterity.addWidget(player.tab.stealth_field, 6, 6, 1, 1)
player.tab.description_dexterity_labl = QtWidgets.QLabel(player.tab.characteristics_dexterity)
player.tab.description_dexterity_labl.setGeometry(QtCore.QRect(7, 190, 311, 231))
player.tab.description_dexterity_labl.setTextFormat(QtCore.Qt.AutoText)
player.tab.description_dexterity_labl.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
player.tab.description_dexterity_labl.setWordWrap(False)
player.tab.description_dexterity_labl.setOpenExternalLinks(False)
player.tab.description_dexterity_labl.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
player.tab.description_dexterity_labl.setObjectName("description_dexterity_labl")
player.tab.caractersistics.addTab(player.tab.characteristics_dexterity, "")
player.tab.characteristics_bodybuild = QtWidgets.QWidget()
player.tab.characteristics_bodybuild.setObjectName("characteristics_bodybuild")
player.tab.gridLayoutWidget_3 = QtWidgets.QWidget(player.tab.characteristics_bodybuild)
player.tab.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 311, 63))
player.tab.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
player.tab.gridLayout_3 = QtWidgets.QGridLayout(player.tab.gridLayoutWidget_3)
player.tab.gridLayout_3.setContentsMargins(10, 0, 0, 0)
player.tab.gridLayout_3.setObjectName("gridLayout_3")
player.tab.line_70 = QtWidgets.QFrame(player.tab.gridLayoutWidget_3)
player.tab.line_70.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_70.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_70.setObjectName("line_70")
player.tab.gridLayout_3.addWidget(player.tab.line_70, 1, 1, 1, 1)
player.tab.line_71 = QtWidgets.QFrame(player.tab.gridLayoutWidget_3)
player.tab.line_71.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_71.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_71.setObjectName("line_71")
player.tab.gridLayout_3.addWidget(player.tab.line_71, 1, 2, 1, 1)
player.tab.line_69 = QtWidgets.QFrame(player.tab.gridLayoutWidget_3)
player.tab.line_69.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_69.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_69.setObjectName("line_69")
player.tab.gridLayout_3.addWidget(player.tab.line_69, 1, 0, 1, 1)
player.tab.line_72 = QtWidgets.QFrame(player.tab.gridLayoutWidget_3)
player.tab.line_72.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_72.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_72.setObjectName("line_72")
player.tab.gridLayout_3.addWidget(player.tab.line_72, 1, 3, 1, 1)
player.tab.bodybuild_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_3)
player.tab.bodybuild_field.setObjectName("bodybuild_field")
player.tab.gridLayout_3.addWidget(player.tab.bodybuild_field, 0, 1, 1, 1)
player.tab.save_giving_bodybuild_checkboxhaving = QtWidgets.QCheckBox(player.tab.gridLayoutWidget_3)
player.tab.save_giving_bodybuild_checkboxhaving.setObjectName("save_giving_bodybuild_checkboxhaving")
player.tab.gridLayout_3.addWidget(player.tab.save_giving_bodybuild_checkboxhaving, 2, 2, 1, 1)
player.tab.mod_bodybuild_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_3)
player.tab.mod_bodybuild_field.setObjectName("mod_bodybuild_field")
player.tab.gridLayout_3.addWidget(player.tab.mod_bodybuild_field, 0, 3, 1, 1)
player.tab.znachenie_bodybuild_labl = QtWidgets.QLabel(player.tab.gridLayoutWidget_3)
player.tab.znachenie_bodybuild_labl.setObjectName("znachenie_bodybuild_labl")
player.tab.gridLayout_3.addWidget(player.tab.znachenie_bodybuild_labl, 0, 0, 1, 1)
player.tab.save_giving_bodybuild_labl = QtWidgets.QLabel(player.tab.gridLayoutWidget_3)
player.tab.save_giving_bodybuild_labl.setObjectName("save_giving_bodybuild_labl")
player.tab.gridLayout_3.addWidget(player.tab.save_giving_bodybuild_labl, 2, 0, 1, 1)
player.tab.mod_bodybuild_labl = QtWidgets.QLabel(player.tab.gridLayoutWidget_3)
player.tab.mod_bodybuild_labl.setObjectName("mod_bodybuild_labl")
player.tab.gridLayout_3.addWidget(player.tab.mod_bodybuild_labl, 0, 2, 1, 1)
player.tab.line_73 = QtWidgets.QFrame(player.tab.gridLayoutWidget_3)
player.tab.line_73.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_73.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_73.setObjectName("line_73")
player.tab.gridLayout_3.addWidget(player.tab.line_73, 3, 0, 1, 1)
player.tab.line_74 = QtWidgets.QFrame(player.tab.gridLayoutWidget_3)
player.tab.line_74.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_74.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_74.setObjectName("line_74")
player.tab.gridLayout_3.addWidget(player.tab.line_74, 3, 1, 1, 1)
player.tab.line_75 = QtWidgets.QFrame(player.tab.gridLayoutWidget_3)
player.tab.line_75.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_75.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_75.setObjectName("line_75")
player.tab.gridLayout_3.addWidget(player.tab.line_75, 3, 2, 1, 1)
player.tab.line_76 = QtWidgets.QFrame(player.tab.gridLayoutWidget_3)
player.tab.line_76.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_76.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_76.setObjectName("line_76")
player.tab.gridLayout_3.addWidget(player.tab.line_76, 3, 3, 1, 1)
player.tab.description_bodybuild_labl = QtWidgets.QLabel(player.tab.characteristics_bodybuild)
player.tab.description_bodybuild_labl.setGeometry(QtCore.QRect(10, 70, 311, 271))
player.tab.description_bodybuild_labl.setTextFormat(QtCore.Qt.AutoText)
player.tab.description_bodybuild_labl.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
player.tab.description_bodybuild_labl.setWordWrap(False)
player.tab.description_bodybuild_labl.setOpenExternalLinks(False)
player.tab.description_bodybuild_labl.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
player.tab.description_bodybuild_labl.setObjectName("description_bodybuild_labl")
player.tab.caractersistics.addTab(player.tab.characteristics_bodybuild, "")
player.tab.characteristics_intellect = QtWidgets.QWidget()
player.tab.characteristics_intellect.setObjectName("characteristics_intellect")
player.tab.gridLayoutWidget_4 = QtWidgets.QWidget(player.tab.characteristics_intellect)
player.tab.gridLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 311, 251))
player.tab.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
player.tab.gridLayout_4 = QtWidgets.QGridLayout(player.tab.gridLayoutWidget_4)
player.tab.gridLayout_4.setContentsMargins(10, 0, 0, 0)
player.tab.gridLayout_4.setObjectName("gridLayout_4")
player.tab.history_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_4)
player.tab.history_field.setObjectName("history_field")
player.tab.gridLayout_4.addWidget(player.tab.history_field, 4, 6, 1, 1)
player.tab.mod_intellect_labl = QtWidgets.QLabel(player.tab.gridLayoutWidget_4)
player.tab.mod_intellect_labl.setObjectName("mod_intellect_labl")
player.tab.gridLayout_4.addWidget(player.tab.mod_intellect_labl, 0, 4, 1, 1)
player.tab.mod_intellect_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_4)
player.tab.mod_intellect_field.setObjectName("mod_intellect_field")
player.tab.gridLayout_4.addWidget(player.tab.mod_intellect_field, 0, 6, 1, 1)
player.tab.line_94 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_94.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_94.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_94.setObjectName("line_94")
player.tab.gridLayout_4.addWidget(player.tab.line_94, 0, 3, 1, 1)
player.tab.analiz_checkboxhaving = QtWidgets.QCheckBox(player.tab.gridLayoutWidget_4)
player.tab.analiz_checkboxhaving.setObjectName("analiz_checkboxhaving")
player.tab.gridLayout_4.addWidget(player.tab.analiz_checkboxhaving, 2, 4, 1, 1)
player.tab.line_80 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_80.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_80.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_80.setObjectName("line_80")
player.tab.gridLayout_4.addWidget(player.tab.line_80, 12, 5, 1, 1)
player.tab.save_giving_intellect_labl = QtWidgets.QLabel(player.tab.gridLayoutWidget_4)
player.tab.save_giving_intellect_labl.setObjectName("save_giving_intellect_labl")
player.tab.gridLayout_4.addWidget(player.tab.save_giving_intellect_labl, 12, 0, 1, 1)
player.tab.line_92 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_92.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_92.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_92.setObjectName("line_92")
player.tab.gridLayout_4.addWidget(player.tab.line_92, 3, 1, 1, 1)
player.tab.religion_labl = QtWidgets.QLabel(player.tab.gridLayoutWidget_4)
player.tab.religion_labl.setObjectName("religion_labl")
player.tab.gridLayout_4.addWidget(player.tab.religion_labl, 10, 0, 1, 1)
player.tab.line_105 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_105.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_105.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_105.setObjectName("line_105")
player.tab.gridLayout_4.addWidget(player.tab.line_105, 3, 0, 1, 1)
player.tab.line_98 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_98.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_98.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_98.setObjectName("line_98")
player.tab.gridLayout_4.addWidget(player.tab.line_98, 1, 6, 1, 1)
player.tab.line_84 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_84.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_84.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_84.setObjectName("line_84")
player.tab.gridLayout_4.addWidget(player.tab.line_84, 5, 6, 1, 1)
player.tab.line_108 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_108.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_108.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_108.setObjectName("line_108")
player.tab.gridLayout_4.addWidget(player.tab.line_108, 2, 3, 1, 1)
player.tab.line_115 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_115.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_115.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_115.setObjectName("line_115")
player.tab.gridLayout_4.addWidget(player.tab.line_115, 11, 0, 1, 1)
player.tab.line_81 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_81.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_81.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_81.setObjectName("line_81")
player.tab.gridLayout_4.addWidget(player.tab.line_81, 13, 1, 1, 1)
player.tab.line_93 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_93.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_93.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_93.setObjectName("line_93")
player.tab.gridLayout_4.addWidget(player.tab.line_93, 2, 5, 1, 1)
player.tab.analiz_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_4)
player.tab.analiz_field.setObjectName("analiz_field")
player.tab.gridLayout_4.addWidget(player.tab.analiz_field, 2, 6, 1, 1)
player.tab.line_109 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_109.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_109.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_109.setObjectName("line_109")
player.tab.gridLayout_4.addWidget(player.tab.line_109, 3, 4, 1, 1)
player.tab.magic_field = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_4)
player.tab.magic_field.setObjectName("magic_field")
player.tab.gridLayout_4.addWidget(player.tab.magic_field, 6, 6, 1, 1)
player.tab.intellect_checkbox = QtWidgets.QLineEdit(player.tab.gridLayoutWidget_4)
player.tab.intellect_checkbox.setObjectName("intellect_checkbox")
player.tab.gridLayout_4.addWidget(player.tab.intellect_checkbox, 0, 2, 1, 1)
player.tab.line_114 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_114.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_114.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_114.setObjectName("line_114")
player.tab.gridLayout_4.addWidget(player.tab.line_114, 1, 1, 1, 1)
player.tab.history_checkboxhaving = QtWidgets.QCheckBox(player.tab.gridLayoutWidget_4)
player.tab.history_checkboxhaving.setObjectName("history_checkboxhaving")
player.tab.gridLayout_4.addWidget(player.tab.history_checkboxhaving, 4, 4, 1, 1)
player.tab.line_78 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_78.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_78.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_78.setObjectName("line_78")
player.tab.gridLayout_4.addWidget(player.tab.line_78, 5, 2, 1, 1)
player.tab.line_110 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_110.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_110.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_110.setObjectName("line_110")
player.tab.gridLayout_4.addWidget(player.tab.line_110, 1, 4, 1, 1)
player.tab.history_labl = QtWidgets.QLabel(player.tab.gridLayoutWidget_4)
player.tab.history_labl.setObjectName("history_labl")
player.tab.gridLayout_4.addWidget(player.tab.history_labl, 4, 0, 1, 1)
player.tab.line_96 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_96.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_96.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_96.setObjectName("line_96")
player.tab.gridLayout_4.addWidget(player.tab.line_96, 12, 3, 1, 1)
player.tab.line_100 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_100.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_100.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_100.setObjectName("line_100")
player.tab.gridLayout_4.addWidget(player.tab.line_100, 0, 5, 1, 1)
player.tab.line_87 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_87.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_87.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_87.setObjectName("line_87")
player.tab.gridLayout_4.addWidget(player.tab.line_87, 3, 6, 1, 1)
player.tab.line_79 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_79.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_79.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_79.setObjectName("line_79")
player.tab.gridLayout_4.addWidget(player.tab.line_79, 1, 0, 1, 1)
player.tab.history_checkbox = QtWidgets.QCheckBox(player.tab.gridLayoutWidget_4)
player.tab.history_checkbox.setObjectName("history_checkbox")
player.tab.gridLayout_4.addWidget(player.tab.history_checkbox, 4, 2, 1, 1)
player.tab.line_104 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_104.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_104.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_104.setObjectName("line_104")
player.tab.gridLayout_4.addWidget(player.tab.line_104, 1, 3, 1, 1)
player.tab.line_107 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_107.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_107.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_107.setObjectName("line_107")
player.tab.gridLayout_4.addWidget(player.tab.line_107, 0, 1, 1, 1)
player.tab.line_95 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_95.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_95.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_95.setObjectName("line_95")
player.tab.gridLayout_4.addWidget(player.tab.line_95, 7, 0, 1, 1)
player.tab.line_85 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_85.setFrameShape(QtWidgets.QFrame.HLine)
player.tab.line_85.setFrameShadow(QtWidgets.QFrame.Sunken)
player.tab.line_85.setObjectName("line_85")
player.tab.gridLayout_4.addWidget(player.tab.line_85, 1, 5, 1, 1)
player.tab.line_88 = QtWidgets.QFrame(player.tab.gridLayoutWidget_4)
player.tab.line_88.setFrameShape(QtWidgets.QFrame.HLine)
